### ISSUE TITLE
Getting error saying : "no sunch file or directlry"

### ISSUE THREAD

**Issue by ssenthil416** [redis/go-redis#1122]
Failed for "github.com/go-redis/redis/v7/internal" (failed to get ignore files): open /builddir/build/BUILD/gopath/.cache/govendor/github.com/go-redis/redis/v7/internal: no such file or directory

**Comment by ssenthil416** [comment]
Failed for "github.com/go-redis/redis/v7/internal" (failed to get ignore files): open /builddir/build/BUILD/gopath/.cache/govendor/github.com/go-redis/redis/v7/internal: no such file or directory

**Comment by vmihailenco** [comment]
It is not clear what you are doing, but you should be using Go modules in order to use v7 - https://github.com/golang/go/wiki/Modules

**Comment by ssenthil416** [comment]
We are using vendor still, so we try to pull we are getting this error

**Comment by ssenthil416** [comment]
We are using govendor still in our env. So when we do govendor sync, it gives problem with that error... So can you please give govendor support too

**Comment by vmihailenco** [comment]
I guess you need to stay on v6.15.3 and consider upgrading to Go Modules. Even https://github.com/kardianos/govendor says "Use Go modules".

**Comment by fari-99** [comment]
in my go project, i used glide, and have this problem when use `glide cc && glide update` on my mac, what i'm doing is

1. add version on my glide.yaml
2. remove glide.lock and vendor (opsional) `rm -rf vendor/ && rm -rf glide.lock`
3. `glide cc && glide install` (or `glide update`)

hope it's help.

**Comment by KNCal** [comment]
There is no "v7" directory under "github.com/go-redis/redis". All references to "github.com/go-redis/redis/v7" should be corrected to "github.com/go-redis/redis".
