### ISSUE TITLE
Run fn ForEachMaster sequentially

### ISSUE THREAD

**Issue by kentakozuka** [redis/go-redis#1249]
I am using `ClusterClient.ForEachMaster` in clusters.
The doc says:

> ForEachMaster concurrently calls the fn on each master node in the cluster. It returns the first error if any. 

But, for avoiding huge CPU usage, I want to execute `fn` on each master node sequentially.
Is there a way to do that?

**Comment by wziww** [comment]
You can ask each master node sequentially with creating temporary client by yourself.
Such as 
``` golang
tmpClient := redis.NewClient(&redis.Options{
			Addr:     host + ":" + port,
			Password: c.password,
		})
		defer tmpClient.Close()
		result, err := tmpClient.Eval(xxxxx).Result()
```

**Comment by kentakozuka** [comment]
Looks nice!
Let me try this idea 👍

**Comment by kentakozuka** [comment]
Seems that there is no method to return all master nodes.
So I should call `ForEachMaster` to get them all and execute commands for each node. Is that right?
