### ISSUE TITLE
PubSub documentation example unclear on concurrent use

### ISSUE THREAD

**Issue by mgale** [redis/go-redis#1271]
The following example exist in the docs:
https://godoc.org/github.com/go-redis/redis#ex-PubSub

1. pubsub := rdb.Subscribe("mychannel1")
2. 
3. // Wait for confirmation that subscription is created before publishing anything.
4. _, err := pubsub.Receive()
5. if err != nil {
6.     panic(err)
7. }
8. 
9. // Go channel which receives messages.
10. ch := pubsub.Channel()
11. 
12. // Publish a message.
13. err = rdb.Publish("mychannel1", "hello").Err()
14. if err != nil {
15.     panic(err)
16. }
17. 
18. time.AfterFunc(time.Second, func() {
19.     // When pubsub is closed channel is closed too.
20.     _ = pubsub.Close()
21. })
22. 
23. // Consume messages.
24. for msg := range ch {
25.     fmt.Println(msg.Channel, msg.Payload)
26. }

Based on the documentation it seems that:
- code between lines 1-8 are not safe for concurrent use. 
- code between line 10 is safe for concurrent use.

I am struggling to determine the correct setup for an app that has long lived connections, where each connection could be subscribed to the same topic, for example topicfoobar or each connection has it's own topic. 

In my example I can have multiple consumers that all need a copy of the message from the producer. 

It is possible to update the documentation or provide an example how to handle multiple consumers for dynamic topics.

**Comment by undercover87** [comment]
+1 
I am using a global redis Client and I launch a number of goroutines that each "psubscribe" to a different key, _i.e._ each goroutine has a snippet of this form :
`
PubSub := redisClient.PSubscribe(ctx, keys...)
msgi, err := PubSub.Receive(context.Background())
... do something with msgi ...
`

I am confused if this is safe for concurrent use or if this is indeed the case the documentation of Psubscribe is referring to ("not safe for use by multiple goroutines").
