### ISSUE TITLE
Use an interface for logging

### ISSUE THREAD

**Issue by aksdb** [redis/go-redis#1279]
Currently `internal.Logger` is defined as being `*log.Logger`; a pointer to a struct. This makes it impossible to use a custom logger. We either have to live with the stdlib logger or disable logging (or implement some awful hacks involving the writer).

All that is used throughout the library however is `Printf(...)`. Therefore I propose to instead define a slim interface with only the method required and use that. The stdlib logger can still be the default, but at least it's possible then to easily replace it with a truly custom implementation.

**Comment by KevinAnthony** [comment]
I like this as a first step, but it would be nice if it implemented at the very least err/info.
