### ISSUE TITLE
Redis Cluster don't support fullly pubsub expired events

### ISSUE THREAD

**Issue by Nassue** [redis/go-redis#1280]

**Comment by Nassue** [comment]
hello, i try it, pubsub "__keyevent@0__:expired", redis cluster just return special node connection
![image](https://user-images.githubusercontent.com/23072882/77522896-f0717e00-6ebf-11ea-9b5d-69dda71594e0.png)

**Comment by garima803** [comment]
@Nassue : Did you find answer for your question as I am also trying to solve same issue.
