### ISSUE TITLE
Unclear how to get values from pipeline.Exec()

### ISSUE THREAD

**Issue by ihsw** [redis/go-redis#13]
Hi, I'm not sure how to get values from `pipeline.Exec()`.

`cmd.Val()` results in `type redis.Cmder has no field or method Val`

It's very odd because `reflect.TypeOf(cmd)` does indeed return `*redis.StringCmd`, and both the docs and the code quite clearly indicate that the `Val()` method should be working.

**Comment by HuanGong** [comment]
the follow link broken，
http://godoc.org/github.com/vmihailenco/redis/v2#example-Client-Pipelined http://godoc.org/github.com/vmihailenco/redis/v2#example-Pipeline
I Got A Error ‘redis: nil’ when i execute code as below:
```go
	pip := redisClient.Pipeline()
	if _, err := pip.Ping().Result(); err != nil {
		log.Errorln("redis pipeline ping failed, err:", err.Error())
	} else {
		//here is ok
		log.Errorln("redis pipeline ping ok")
	}
	results := make([]*redis.StringCmd, 0)
	for _, key := range keys {
		results = append(results, pip.Get(key))
	}
	_, err := pip.Exec()
	if err != nil {
		return make([]int64, len(keys)), errors.Wrapf(err, "Redis Pipeline Execute Error")
	}
```

**Comment by pedrobertao** [comment]
You have to check if the err is equal to `redis.Nil`

```
res, err := pipeline.Exec(ctx)
if err != redis.Nil {
	log.Fatal(err)
}
```

**Comment by MatteoGioioso** [comment]
Both links are broken and I cannot find it, but this is what I have worked out.

```
       ......
	pipeline := redisClient.Pipeline()
	pipeline.Get("123")
	pipeline.Get("456")
        ....

	exec, err := pipeline.Exec()
	if err != nil {
		log.Fatal(err)
	}

	results := make([]*redis.StringCmd, 0)
	for _, cmder := range exec {
		results = append(results, cmder.(*redis.StringCmd))
	}

	fmt.Printf("%+v\n", results[0].Val())
```

But I am not 100% sure this is correct

**Comment by vmihailenco** [comment]
Docs for pipelines are at https://redis.uptrace.dev/guide/pipelines.html . Let me know if anythign is missing.
