### ISSUE TITLE
What's the difference between SentinelClient and FailoverClient?

### ISSUE THREAD

**Issue by leaxoy** [redis/go-redis#1310]
First, I think SentinelClient is used redis sentinel strategy, but then I find there is FailoverClient which use sentinel strategy in it's comments. Now, I'm so confused, can someone explain difference between the two clients.

**Comment by tomnlittle** [comment]
https://github.com/go-redis/redis/issues/1179

**Comment by jwrookie** [comment]
I also faced this problem...

**Comment by dmitsh** [comment]
I created issue #1451

**Comment by deividaspetraitis** [comment]
I'm not sure I am referring to newer version but as per method [NewFailoverClient documentation](https://pkg.go.dev/github.com/go-redis/redis/v8#NewFailoverClient ) it already offers automatic failover:

> NewFailoverClient returns a Redis client that uses Redis Sentinel for automatic failover. It's safe for concurrent use by multiple goroutines.

However if you want to iterate and create failover mechanics by your own you can use `NewSentinelClient` in your business logic as it is done in `NewFailoverClient` implementation, for example: https://github.com/go-redis/redis/blob/v8.3.3/sentinel.go#L512

**Comment by jwrookie** [comment]
thanks



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年11月5日(星期四) 凌晨0:56
收件人: "go-redis/redis"<redis@noreply.github.com&gt;; 
抄送: "为为"<976668992@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [go-redis/redis] What&#39;s the difference between SentinelClient and FailoverClient? (#1310)





 
I'm not sure I am referring to newer version but as per method NewFailoverClient documentation it already offers automatic failover:
  
NewFailoverClient returns a Redis client that uses Redis Sentinel for automatic failover. It's safe for concurrent use by multiple goroutines.
  
However if you want to iterate and create failover mechanics by your own you can use NewSentinelClient in your business logic as it is done in NewFailoverClient implementation, for example: https://github.com/go-redis/redis/blob/v8.3.3/sentinel.go#L512
