### ISSUE TITLE
Limiter on the cluster client?

### ISSUE THREAD

**Issue by ThomasJannaud** [redis/go-redis#1311]
There is a "Limiter" for the redis client but not for the cluster client. Is it as easy as adding it in the options or is there some limitation?
Side note I wanted to make a pull request for this but I cannot push a new branch, what's the process to become a contributor?

**Comment by YiweiZhuang** [comment]
i add one
https://github.com/go-redis/redis/pull/1316

**Comment by walktall** [comment]
@vmihailenco Hi, any thoughts on this?

**Comment by GilbertGeliba** [comment]
I think you can do something like this in v9.0.5
```
			l := &limiter{} // limiter implements the Limiter interface
			c := redis.NewClusterClient(&redis.ClusterOptions{})
			c.OnNewNode(func(rdb *redis.Client) {
				rdb.Options().Limiter = l
			})
```
