### ISSUE TITLE
"ERR wrong number of arguments for 'auth' command" after updating to v8

### ISSUE THREAD

**Issue by Vindexus** [redis/go-redis#1343]
I'm using the the `parseURL` function and connecting works fine when using a simple localhost connection string, but when using our production string that has username and password I get the err above.

Working fine:
```
info, err := redis.ParseURL("redis://localhost:6379")
if err != nil {
	return nil, err
}
c, err = redis.NewClient(info), nil
// err == nil
```

Giving error:
```
info, err := redis.ParseURL("redis://admin:p4ssw0rd@10.20.30.40:4325")
if err != nil {
	return nil, err
}
c, err = redis.NewClient(info), nil
// err.Error() == "ERR wrong number of arguments for 'auth' command"
```

I'm kind of at a loss for how to proceed, so any help is appreciated!

**Comment by flyingrx** [comment]
what is your redis version?  The username is supported after 6.0. 

by the way, it's dangerous to display your username and password.

**Comment by Vindexus** [comment]
I did some investigating and if I go back to go-redis/redis/v7@7.0.0-beta.4 (which I was using previously) I do not get this error message.

If I up to 7.3.0 however, I do get this error.

Redis version is 4.0.9 on production server and 3.2.0 on development machine.

Thanks, those are just example credentials though, they aren't real :)

**Comment by Anhui-tqhuang** [comment]
i meet the same problem
for redis 6 and greater, nothing changes
for lesser, i fix it by setting `username` as `""` and it works for me.

**Comment by pablocrivella** [comment]
Having the same error using the latest v8 beta of go-redis and redis v5

**Comment by novolog** [comment]
same issue using v8.0 beta v5 with Heroku redis (5.0.8)

**Comment by vmihailenco** [comment]
From what I've heard the problem is that your connection string contains a fake username `redis://admin:p4ssw0rd@10.20.30.40:4325` - `admin` in this case. The fix is to remove username before connecting:

```
info, err := redis.ParseURL("redis://admin:p4ssw0rd@10.20.30.40:4325")
if err != nil {
	return nil, err
}
info.Username = ""
rdb := redis.NewClient(info)
```

**Comment by bobber205** [comment]
Just had this issue with after upgrading from `3.0.2` to `3.1.0` on heroku (Looks like fake username issue, username is 'h')

**Comment by nao0x2c6** [comment]
> Just had this issue with after upgrading from `3.0.2` to `3.1.0` on heroku (Looks like fake username issue, username is 'h')

I also met the above issue and found the info:
https://devcenter.heroku.com/changelog-items/1932

**Comment by desduvauchelle** [comment]
Does anybody have a solution for this? Also having the issue.

**Comment by bobber205** [comment]
@desduvauchelle There is an easy solution.

My redis connection string had a username in it like this 
```
h:thisisapassword`
```

I went on heroku and changed it to 

```
:h:thisisapassword
````

and it works! Just make sure you leave the `:`

**Comment by younes-io** [comment]
This worked for me:

```ts
const url = `rediss://:${REDIS_PWD}@${REDIS_HOST}:${REDIS_PORT}`;

const redisClient = createClient({
      socket: {
          url: url,
      },
  });

redisClient
  .connect()
  .then((res) => logger.info(`Redis client is connected.`))
  .catch((err) =>
      logger.error(`Error while trying to connect to Redis: ${err}`),
  );
    
```

**Comment by Fifpoet** [comment]
> i meet the same problem for redis 6 and greater, nothing changes for lesser, i fix it by setting `username` as `""` and it works for me.

I'm trying to connect to Redis3.2 using DataGrip, but it went wrong. When I type nothing in `username`, it not reply, so I type `""`, it works. Thanks, you are my hero.
