### ISSUE TITLE
Regression: ZADD scores are using exponents

### ISSUE THREAD

**Issue by lionello** [redis/go-redis#1345]
The current version in `master` uses `fmt.Sprint` for `float64` args, causing strings such as `"1.590540802326684e+18"`:
https://github.com/go-redis/redis/blob/3d03b1fa6a1ed0775d4b032861da0637b45437da/command.go#L103

This is a regression caused by https://github.com/go-redis/redis/commit/0944d0167b5886c195a151a5553b9fbdff0815d7 where `formatFloat` got removed.

Expected:
`client.ZAdd(ctx, "key", &redis.Z{1590540802326684000.0,"test"})` should result in Redis command `ZADD key 1590540802326684000 test`.

Suggested fix: add a `case float64:` to `func appendArg` doing the same `strconv.FormatFloat` as before: `strconv.FormatFloat(f, 'f', -1, 64)`

**Comment by vmihailenco** [comment]
The current version in master uses https://github.com/go-redis/redis/blob/master/internal/proto/writer.go#L86-L89 which should correctly append floats. Do you have code that demonstrates the problem?

**Comment by lionello** [comment]
Hmm, it's fairly easy to repro:
```go
package main

import (
	"context"
	"github.com/go-redis/redis/v8"
)

func main() {
	client := redis.NewClient(&redis.Options{})
	client.ZAdd(context.TODO(), "test", &redis.Z{Score: 1e23, Member: "x"})
}
```

Result:
```
$ redis-cli zrange test 0 0 withscores 
1) "x"
2) "9.9999999999999992e+22"
```

**Comment by tejaswinibussety** [comment]
Hi, I'm facing the same issue.
I'm using:  `github.com/go-redis/redis/v8 v8.8.2`

I think this is the latest version available, any help is appreciated.
