### ISSUE TITLE
connect: invalid argument - whenever trying to make a get request

### ISSUE THREAD

**Issue by yan6pz** [redis/go-redis#1362]
Using the release version of the go-redis module`v7.3.0`

And initializing the redis client like below, where config is map[string]string:
  
```GO
db, err := strconv.Atoi(config["db"])
	if err != nil {
		panic(err)
	}
	address := config["host"] + ":" + config["port"]
	pass := config["pass"]

	client := redis.NewClient(&redis.Options{
		Addr:     address,
		Password: pass,
		DB:       db,
	})

	val, err := client.Get(hashKey).Result()
```
Whenever the Get runs I am getting an error like the following:

`http2: panic serving 172.23.0.1:36234: dial tcp 0.0.0.172:6379: connect: invalid argument`

Any ideas what exactly may be causing it?

**Comment by vmihailenco** [comment]
`0.0.0.172` looks suspicious. Good chances are you can't use IPs starting with `0`.
