### ISSUE TITLE
Nil error should include key name

### ISSUE THREAD

**Issue by mperham** [redis/go-redis#1366]
Hi, thank you so much for building and maintaining this project!

I'd like to suggest a small improvement: can `redis.Nil` include the name of the key that was not found? This would make a huge improvement in tracking down nil errors for apps which use Redis heavily.

**Comment by vmihailenco** [comment]
This would require updating a lot of user code to use `redis.IsNil(err)` or something for a moderately useful change. This does not look like the right trade-off...
