### ISSUE TITLE
read-write separation

### ISSUE THREAD

**Issue by jiuker** [redis/go-redis#1367]
Our program only needs to execute commands, and we don't care about the result failure. If it fails, it's just an alarm and doesn't do other operations. When I try to use pipeline, I find a problem. Pipeline will confirm the result every time, and the result will be delayed (70ms). If we have 1000 times of pipeline, that is, we need at least 70s to send it. Can I support read-write separation?

**Comment by vmihailenco** [comment]
No, that is not supported. Are you aware of any other Redis clients that support this?

**Comment by jiuker** [comment]
https://github.com/gomodule/redigo
this pkg support,like 
```
   go fun(){
       for{
           Receive()
       }
   }()
   for{
      Do()
      Do()
      Flush()
   }

```

**Comment by tong3jie** [comment]
https://github.com/meitu/go-redis-pool

**Comment by tong3jie** [comment]
@vmihailenco
