### ISSUE TITLE
ERR Client sent AUTH, but no password is set

### ISSUE THREAD

**Issue by Tyxiang** [redis/go-redis#1376]
## Code

```go
package main

import (  
    "github.com/gin-gonic/gin"
    "context"
    "github.com/go-redis/redis/v8"
    "fmt"
)

var ctx = context.Background()

func main() {
    router := gin.Default()

    client := redis.NewClient(&redis.Options{
        Addr:     "mydomain:8008",
        Password: "mypass",
        DB:       0,
    })

    pong, err := client.Ping(ctx).Result()
    fmt.Println(pong, err)

    router.Run()
}
```

## Error
` ERR Client sent AUTH, but no password is set`

## Other
- Everything works fine when connected via redis-cli with the same password.
- There is the same problem in v7.

**Comment by yinyicao** [comment]
I also encountered the same problem. There are two redis instances under k8s service, one with a password and one without

**Comment by ofekshenawa** [comment]
Hi @Tyxiang,

Thank you for bringing this issue to our attention. I have investigated the problem and found a solution using the "github.com/redis/go-redis/v9" package. Here is an example code that demonstrates how to create a connection using a password:

```go
package main

import (
	"context"
	"fmt"

	"github.com/redis/go-redis/v9"
)

var ctx = context.Background()

func main() {
	client := redis.NewClient(&redis.Options{
		Addr:     "address:6379",
		Password: "Password",
		DB:       0,
	})

	pong, err := client.Ping(ctx).Result()
	fmt.Println(pong, err)
}
```

We appreciate your contribution to improving our project and hope that this solution resolves the issue to your satisfaction. We will be closing this issue, but if you continue to experience any problems, please don't hesitate to let us know and we will be happy to reopen it for further investigation.

Thank you again for your support.
