### ISSUE TITLE
over 60 "cluster slots" commands per second when using the ClusterClient type

### ISSUE THREAD

**Issue by tancehao** [redis/go-redis#1390]
makes the first node's cpu usage among the cluster containing 100 masters and 100 slaves becomes too high.
would you please give me some tips?

**Comment by vmihailenco** [comment]
You can try https://github.com/go-redis/redis/pull/1391/files which picks random node for loading cluster slots.

`cluster slots` command is issued on every error except `redis: nil` (but not more often than once in 100ms). If you have lots of errors it can explain high number of `cluster slots`. I assumed it should be harmless.
