### ISSUE TITLE
Adding metrics instrumentation for OpenTelemetry

### ISSUE THREAD

**Issue by TigerHe7** [redis/go-redis#1392]
@reggiemcdonald and I were looking into adding a Redis integration for OpenTelemetry, but noticed support for tracing has already been added to this repo.

We're wondering if we can pursue **adding metrics instrumentation for OpenTelemetry** to this repository?

Just wanted to request permission (perhaps from @vmihailenco) before getting started!

**Comment by vmihailenco** [comment]
@TigerHe7 that sounds good - please go ahead! If you have a list of metrics you would like to add - please share the list. Also it would be easier if your first PR contains single metric so we have a chance to discuss high level details before adding too many metrics.

I am not overly familiar with metrics myself but these links should be helpful
- https://github.com/open-telemetry/oteps/pull/108/files
- https://github.com/open-telemetry/opentelemetry-specification/pull/657/files

**Comment by reggiemcdonald** [comment]
@vmihailenco I noticed that the otel hook will only record spans if a parent exists in the context. Is this the intended behaviour?
Code for reference:
https://github.com/go-redis/redis/blob/dc52593c8c63bc2a05796ec44efd317fd3e14b64/redisext/otel.go#L18-L21

**Comment by vmihailenco** [comment]
@reggiemcdonald yes, that is intended. The assumption is that there should be a parent span when OpenTelemetry is used. Usually it is a span for HTTP handler / queue handler. Does it cause any problems?

**Comment by reggiemcdonald** [comment]
Great to know, thanks! 

Would you mind if I updated the docs to make this more clear for future users?

**Comment by TigerHe7** [comment]
@reggiemcdonald and I thinking of adding these additional metrics to this Redis client, based on the previous OpenCencus integration: https://github.com/opencensus-integrations/redis/pull/1/files#diff-cbb25aea043ef5888a4f0283ee00649aR20-R33

We currently already track the number of write commands and new connections created. 

Do @vmihailenco or @MrAlias have any thoughts, or does this seem reasonable?
