### ISSUE TITLE
Convenience method for checking for Nil error

### ISSUE THREAD

**Issue by gidyon** [redis/go-redis#1402]
First, thank you for maintaining the project. Can you add support for checking if an error returned from redis is Nil (get on non-existent key). This will eliminate unnecessary boilerplates. Thank you!

**Comment by gidyon** [comment]
`errors.Is(err, redis.Nil)` works because `redis,Nil` is an error, but since the type of `redis.Nil `is resides under` internal/`, the type is not visible to the public.

**Comment by oAnubis** [comment]
Depending on your specific application uses you can write a ParseResult function “override” the results similar to overriding MarshalJson to fit your specific application use cases.

**Comment by oAnubis** [comment]
You could write a quick override for this to fit your application needs. 
I've found it helpful to sometimes not treat redis.Nil as an error, allowing the Val() method to assign the zero value instead of 
returning early.

```
type NR interface {
	redis.Cmder
}

func Parse[E NR](cmd E) error {
    switch {
    case cmd.Err() == redis.Nil:
        return nil
    default:
        return cmd.Err()
    }
}
````
