### ISSUE TITLE
blpop of go-redis v8 In the environment of redis 5.0.8, the timeout parameter is invalid. Normal under redis 4.0.1 environment

### ISSUE THREAD

**Issue by leonwanggl** [redis/go-redis#1424]
`for{
		stringSlice := util.Rdb.BLPop(util.Ctx, 5*time.Second, "apns_pushQueue")
		log.Println("for ",5*time.Second)
}
`
###  Output in the environment of redis5.0.8
![image](https://user-images.githubusercontent.com/26614511/88462333-3d507a00-cedd-11ea-9b3c-e7e1af56c3dc.png)

###  Output in the environment of redis4.0.11
![image](https://user-images.githubusercontent.com/26614511/88462366-6a049180-cedd-11ea-9436-4e4f7b1cb8c5.png)

**Comment by vmihailenco** [comment]
Can it be that `util.Ctx` has a deadline?
