### ISSUE TITLE
Add ability to route based on "addr"

### ISSUE THREAD

**Issue by bogdandrutu** [redis/go-redis#1438]
My scenario is (probably common), I deployed Redis in an AWS with master and read-only replicas across multiple AZs (traffic is 99% read). I would like if possible to redirect the majority of the reads to read-only replicas in the same AZ to avoid cross AZ network traffic ($$$).

Initial thought was to support a custom "router" a func that allows user to sort nodes in the order of priorities (I will do it based on address most likely, maybe it is not possible).

Do you have a solution for this? Does anyone solved this issue?

PS: "RouteByLatency" may be good, but the problem is that if `updateLatency` will give a bad latency (for different reasons) initially I will end-up never going to the same AZ. A solution may be to run periodically `updateLatency`.

**Comment by vmihailenco** [comment]
I've improved RouteByLatency in https://github.com/go-redis/redis/pull/1484:
- latency should be more accurate by properly calculating mean and inserting random pauses between probes
- latency should be updated when Cluster state changes

Hopefully that is enough.
