### ISSUE TITLE
[Major BUG] Shouldn't retry on network errors(timeouts) when treating MaxRedirects in cluster mode

### ISSUE THREAD

**Issue by duke-cliff** [redis/go-redis#1481]

**Comment by duke-cliff** [comment]
https://github.com/go-redis/redis/blob/655eaaa39d11b24701711bf282f6e00b62e32663/cluster.go#L817

We recently had a Redis outage issue because of this, our network payload out of Redis became significantly larger which exceeds the AWS single elasticate bandwidth limit(10Gbps). Redis-go client will receive connection/read timeout because of the bandwidth is capped by AWS for new connections. But the. current Redis-go logic will just keep retrying and spawning new commands/connections(160K connections per node) to Redis eventually exhausted the whole Redis.

I have compared the logic with Spring-redis: 

https://github.com/spring-projects/spring-data-redis/blob/2bcb06acc88ee23d2d355568ed96ca303d9f86a3/src/main/java/org/springframework/data/redis/connection/ClusterCommandExecutor.java#L143


https://github.com/spring-projects/spring-data-redis/blob/289fa1acb9f790a90adcc488c2c24223e8ab6987/src/main/java/org/springframework/data/redis/ClusterRedirectException.java#L21

Clearly spring-redis will `ONLY` do retries when received `ClusterRedirectException(move)` .

This bug won't be easily noticed until you have constantly large throughput + network becomes slow all of sudden(bandwidth got throttled) 

Suggestions:
1) Don't retry on network errors for redirects
2) Gives an option to skip retries on network errors, but retry on move/read only or other cluster errors

**Comment by vmihailenco** [comment]
Comment on `MaxRedirects` says that "Command is retried on network errors and MOVED/ASK redirects". Overall retrying on network errors is a common thing. And given that a Redis Cluster must have read only nodes it makes sense to try command on another (slave) node (at least for read-only commands).

I am not sure that disabling network retries is a good thing and that go-redis misbehaves here. But perhaps we should lower default `MaxRedirects`.

**Comment by duke-cliff** [comment]
Hi @vmihailenco , there's also a `MaxRetries` in the `ClusterOption`. What I believe the correct behavior should be:
1) `MaxRedirects` only do retries if it's an expected `Redirect Error(MOVED/ASK)`
2) `MaxRetries` gives the option for user to decide if we want to retry the commands on network errors(`retriable`)

Normally, the command retry due to unavailable Redis should happen in the business logic, not at the driver level. Here are some reasons:
1) The business logic doesn't want to retry `WRITES` in general, especially `INCR/DECR`. 
2) In most cases, the business logic can skip`READS` retries as well, if reads on Redis failed, we could fallback to msql/postgres or just simply returns error to client
3) I believe the default value of `MaxRetries` is 0. It will skip network error retries for the `Single` mode. But it's not respected in the `Cluster-Mode`.

**Comment by duke-cliff** [comment]
I also prepared a PR for this: https://github.com/go-redis/redis/pull/1487
