### ISSUE TITLE
ping method with ClusterClient

### ISSUE THREAD

**Issue by wziww** [redis/go-redis#1498]
## Expected Behavior
`ping` method should right to the target remote address while using `ClusterClient`, this method usually used to do the heathy check with the target remote address.

## Current Behavior
`ping` the redis node randomly

**Comment by wziww** [comment]
Like this situation https://github.com/go-redis/redis/issues/1327#issuecomment-694621958 may confusing

**Comment by vmihailenco** [comment]
And what is the target when you write `rdb.Ping(ctx)`?

**Comment by wziww** [comment]
Like `redis-cli`, when we exec `redis-cli -h 10.0.6.49 -p 6379 -c PING`, the command will be send to 10.0.6.49:6379 and get reply from it, but with `ClusterClient `,we dont know where the command will be sent to and we cant control it.
