### ISSUE TITLE
NX parameter missing for EXPIRE command

### ISSUE THREAD

**Issue by bmassemin** [redis/go-redis#1862]
According to https://redis.io/commands/expire the `EXPIRE` command can have the `NX` parameter.
I can't find a command like `ExpireNX()` or a parameter for `Expire()`

Am I missing something ?
Thanks 🙏

**Comment by monkey92t** [comment]
Yes, it is a new option added by redis7.0, go-redis has not been updated yet.

**Comment by bmassemin** [comment]
Can I push a PR with this new method or usually the maintainers are developing all the new features of an engine all at once?

**Comment by monkey92t** [comment]
Yes, welcome

**Comment by monkey92t** [comment]
> Can I push a PR with this new method or usually the maintainers are developing all the new features of an engine all at once?

If you perform unit tests locally, you can try this tool ([grte](https://github.com/monkey92t/grte)), it is still in the testing phase

**Comment by dpandey5515** [comment]
when are u planning to release the new version @DaemonSnake
