### ISSUE TITLE
SetLogger takes an internal type, which is not accessible from external code

### ISSUE THREAD

**Issue by shassard** [redis/go-redis#1892]
https://github.com/go-redis/redis/blob/997118894af9d4244d4a471f2b317eead9c9ca62/redis.go#L18

In v7 SetLogger() takes a *log.Logger object, which can be passed in easily.

In v8, the type of the argument changed to internal.Logging, which would require importing the internal package to access that type resulting in code that would look something like:
```diff
-       redis.SetLogger(zap.NewStdLog(log))
+       stdlog := interface{}(zap.NewStdLog(log)) // ugly hack to convert the logger into an interface for further type conversion below
+       redis.SetLogger(stdlog.(redisintern.Logging))
```

... but that's actually impossible to do given the enforcement by the Go compiler.

```bash
	main.go:18:2: use of internal package github.com/go-redis/redis/v8/internal not allowed
```

It seems impossible to use SetLogger anymore.

Is it possible to modify the SetLogger function to accept a type that's publicly exposed?

**Comment by xsddz** [comment]
meet same issue, has solution?

**Comment by lev112** [comment]
you don't need to cast to `internal.Logging`, just to make sure that your logger is implementing that interface.

the logger from `zap.NewStdLog(log)` implements the following method:
```
func Printf(format string, v ...interface{})
```

but `internal.Logging` requires this method:
```
func Printf(ctx context.Context, format string, v ...interface{})
```

to make it work, you need to create a new struct that implements that methond

**Comment by baylac** [comment]
Is the logger working at all? I passed my implementation but still dont see anything being logged.

**Comment by smithamax** [comment]
> Is the logger working at all? I passed my implementation but still dont see anything being logged.
+1 here, I'm getting 3 errors when if I restart redis, only one is logged through my custom logger

```
level=info service=redis msg="redis: discarding bad PubSub connection: EOF"
redis: 2022/04/28 11:51:40 pubsub.go:159: redis: discarding bad PubSub connection: EOF
redis: 2022/04/28 11:51:40 pubsub.go:159: redis: discarding bad PubSub connection: EOF
```
If I don't use the custom logger all 3 lines are the same

**Comment by smithamax** [comment]
Never mind, I had an orphan process still running :(

**Comment by roman-vynar** [comment]
Same here, v8 breaks logging re-definition. The following is no longer working:
```
	goredis.SetLogger(log.New(&c.goredisLogBuffer, "go-redis ", log.Ldate|log.Ltime|log.Lshortfile))
```
