### ISSUE TITLE
UniversalClient and Unix Sockets

### ISSUE THREAD

**Issue by SergeyTsalkov** [redis/go-redis#1938]
Is it possible for UniversalOptions to support the Options.Network setting? My application has a config file where the user can specify a single redis server (through either tcp or unix sockets), or a redis cluster to talk to. Currently this makes it hard to use UniversalClient because it doesn't support Options.Network, not even when we're using a single redis server.

**Comment by monkey92t** [comment]
```go
client := redis.NewUniversalClient(&redis.UniversalOptions{
        Addrs: ...,
        Dialer: func(ctx context.Context, network, addr string) (net.Conn, error) {
                ....
        },
})
```
