### ISSUE TITLE
Support the 'MONITOR' command

### ISSUE THREAD

**Issue by AlistairBurrowes** [redis/go-redis#2041]
The README has stated something like `Redis 3 commands except QUIT, MONITOR, and SYNC.` for 8 years or so. I am unclear if this deliberate, or if there might be an appetite to support the `MONITOR` command.

My company has a requirement for this. We may be able to contribute support, but of course guidance around implementation would be desirable. Can it be confirmed if `MONITOR` support fits the scope of this library?

In terms of implementation, I believe it would be something like `SUBSCRIBE`, but I would need to drill in further to understand the nuance. Thanks!

**Comment by monkey92t** [comment]
From the documentation, MONITOR is just a debugging command, I don't know much about this command, maybe you can try the `client.Do(ctx, cmd...)` method?

**Comment by lsnan** [comment]
+1

**Comment by tiny-craft** [comment]
I also need this command support, for my Redis GUI Client. [Tiny RDM](https://github.com/tiny-craft/tiny-rdm)
