### ISSUE TITLE
redis: can't marshal map[string]main.student (implement encoding.BinaryMarshaler)

### ISSUE THREAD

**Issue by capyun** [redis/go-redis#2086]
Issue tracker is used for reporting bugs and discussing new features. Please use
[stackoverflow](https://stackoverflow.com) for supporting issues.

## Expected Behavior

I hope HSet can support store map[string]struct.

## Current Behavior

redis: can't marshal map[string]main.student (implement encoding.BinaryMarshaler)

## Steps to Reproduce

type student struct {
	Name string
	Age  int
}

func (s student) MarshalBinary() (data []byte, err error) {
	data, err = json.Marshal(&s)
	return
}

func main() {
	rdb := redis.NewClient(&redis.Options{
		Addr:     "localhost:6379",
		Password: "2000.redis",
	})
	m := make(map[string]student)
	m["1"] = student{
		"sxy",
		18,
	}
	m["2"] = student{
		"szw",
		0,
	}
	ctx := context.Background()
	cmd := rdb.HSet(ctx, "student", m)
	fmt.Println(cmd.Err())
	x := rdb.HGet(ctx, "student", "1")
	fmt.Println(x)
}

**Comment by cncap** [comment]
I found this: 
https://redis.io/docs/stack/json/

Requirements:

[Redis v6.0 or above](http://redis.io/download)

Because this is a new mod after redis v6.0, I don't know whether go redis supports it

**Comment by cncap** [comment]
Some mods found in here:
https://github.com/RedisJSON/RedisJSON

[go-rejson](https://github.com/nitishm/go-rejson/)	Go	MIT	
[rejonson](https://github.com/KromDaniel/rejonson)	Go	Apache-2.0
[rueidis](https://github.com/rueian/rueidis)	Go	Apache-2.0
