### ISSUE TITLE
SSUBSCRIBE / SPUBLISH

### ISSUE THREAD

**Issue by aep** [redis/go-redis#2091]
redis now has sharded pub/sub

should those be supported?

**Comment by binhbo12456** [comment]
any news ?

**Comment by syavuz** [comment]
is there any alternative way to use the pub/sub with sharded cluster for now?

**Comment by chayim** [comment]
Given a quick read of [this](https://github.com/redis/go-redis/blob/805bfc2c60546190e6c1a160a279dd6ebe2d6de4/cluster.go#L1695) it would appear we already have support for this, along with [the associated test](https://github.com/redis/go-redis/blob/805bfc2c60546190e6c1a160a279dd6ebe2d6de4/cluster_test.go#L556).

IMHO we can close this.

**Comment by vmihailenco** [comment]
Okay, closing.
