### ISSUE TITLE
client: document threadsafety

### ISSUE THREAD

**Issue by libla** [redis/go-redis#2095]
Go documentation usually follows a rule of: something is only safe for concurrent access if it's explicitly documented to be safe.

I don't see any explicit documentation regarding thread safety on https://redis.uptrace.dev/guide/go-redis.html, so I would assume it is not safe to us a redis client from multiple goroutines.

However, the code does appear to be threadsafe, so perhaps just the docs need updating?

**Comment by vmihailenco** [comment]
We have this information in the reference - https://pkg.go.dev/github.com/go-redis/redis/v8. Search for "It's safe for concurrent". That is the main source of the truth, but we can add something to the docs as well. Do you mind sending a PR?
