### ISSUE TITLE
del multi keys, cross keys in request don't hash to the same slot

### ISSUE THREAD

**Issue by 13881802223** [redis/go-redis#2134]
**Describe the bug**
When deleting multi keys in different slots, i got error below:
CROSSSLOT KEYS in request don't hash to the same slot

How could i del keys in different slots?Which api is suggested?

Please Help me! Thanks a lot

**Comment by bald2b** [comment]
You must separate operations for keys in different slots. 
So group your keys by hashslots, then exec `DEL <keys with same hashslot> ... ` one by one
