### ISSUE TITLE
 How to use TLS with ClusterClient when running Redis Cluster in an environment where the IPs of the nodes’ are dynamic

### ISSUE THREAD

**Issue by AbdullahAlShaad** [redis/go-redis#2136]
I am running a Redis Cluster with 3 masters and 3 replicas. I have 3 shards. In each shard, there is one master and one replica.  I am trying to connect with the cluster using a TLS certificate.

In the certificates SANS field, I have provided the DNS names of the nodes and Local Host IP. As Node IPs are not permanent I can not use static IPs in the certificate.

 The Cluster Options used to create ClusterClient are: 
```
	addresses := []string{redis-cluster-shard0-0.demo.svc,redis-cluster-shard0-1.demo.svc,redis-cluster-shard1-0.demo.svc,...} // DNS names of all the nodes.
	rdOpts := &rd.ClusterOptions{
		DialTimeout: 15 * time.Second,
		IdleTimeout: 3 * time.Second,
		PoolSize:    1,
		Addrs:      addresses,
	}
```

When I try to ping or do any database operation in the cluster using ClusterClient it can not verify the certificate. The error message is 
`x509: certificate is valid for 127.0.0.1, not 10.244.0.55)`

In this case, `10.244.0.55` is the IP of one of the master nodes of the cluster. When ClusterClient is used it moves the request to different nodes using Node IP. Without TLS I can write and read data from any node using ClusterClient.

How can I do cluster operations using ClusterClient with TLS enabled?

**Comment by figaw** [comment]
This is still relevant to us.
