### ISSUE TITLE
The CI pipeline runs `go test ./...`, which only tests the module at the root of the repo

### ISSUE THREAD

**Issue by dcormier** [redis/go-redis#2366]
There are multiple modules in this repo, but the CI pipeline only runs `go test` for the root module, missing compilation issues that currently exist in those other modules.

## Expected Behavior

The CI pipeline should run `go test` for all modules in the repo.

## Current Behavior

`go test` is only run for the `github.com/redis/go-redis/v9` module at the root of the repo.

## Possible Solution

Explicitly run `go test` for all modules in this repo.

## Steps to Reproduce

See that CI passes, despite the fact that #2266 is still a problem, but `go test` catches that problem if it is run for that module.

**Comment by vmihailenco** [comment]
Should be fixed by https://github.com/redis/go-redis/commit/ddb0bc08beba3e01c0943eb054c12e2c8c7567f9

**Comment by dcormier** [comment]
That commit has a syntax error and fails to run.
