### ISSUE TITLE
Error: use of internal package github.com/redis/go-redis/internal not allowed

### ISSUE THREAD

**Issue by jkrcmar** [redis/go-redis#2372]
I destroyed and remade my docker container that imports the redis module and it gives the error: Error: use of internal package github.com/redis/go-redis/internal not allowed

## Expected Behavior

The module should just install, havent had a problem with the module in months utilizing the simple import:
RUN go get github.com/go-redis/redis

## Current Behavior

it gives an error: use of internal package github.com/redis/go-redis/internal not allowed

## Possible Solution

i saw the same error reported somewhere in 2017, may help

## Steps to Reproduce

run go get github.com/go-redis/redis

**Comment by monkey92t** [comment]
No problems found after testing, can you provide the Dockerfile?

**Comment by jkrcmar** [comment]
> No problems found after testing, can you provide the Dockerfile?

https://drive.google.com/file/d/1Mwy85vWURFn0s3s9J9wgVQa2O1fUEGhJ/view?usp=sharing

Really appreciate it

**Comment by monkey92t** [comment]
> > No problems found after testing, can you provide the Dockerfile?
> 
> https://drive.google.com/file/d/1Mwy85vWURFn0s3s9J9wgVQa2O1fUEGhJ/view?usp=sharing
> 
> Really appreciate it

go-redis requires go mod (GO111MODULE=on)

**Comment by jkrcmar** [comment]
Thanks!!!
