### ISSUE TITLE
Add support for BZMPOP command

### ISSUE THREAD

**Issue by chayim** [redis/go-redis#2384]
Redis BZMPOP command was added in version 7.0.0 and is currently supported by the library. We should add support as documented [here](https://redis.io/commands/BZMPOP).

**Comment by SoulPancake** [comment]
@chayim As I had recently completed the support for ZMPOP, Can I also be assigned to take this?

**Comment by yikuaibro** [comment]
> @chayim As I had recently completed the support for ZMPOP, Can I also be assigned to take this?

I'm done, thanks for your ZMPOP contribution. I also learned a lot.

**Comment by chayim** [comment]
@SoulPancake looks like @yikuaibro beat + merged
