### ISSUE TITLE
Add support for FUNCTION KILL command

### ISSUE THREAD

**Issue by chayim** [redis/go-redis#2398]
Redis FUNCTION KILL command was added in version 7.0.0 and is currently supported by the library. We should add support as documented [here](https://redis.io/commands/FUNCTION-KILL).

**Comment by chayim** [comment]
@elena-kolevska Did you get started on this as we were discussing? Can you and @dwibedis sync to make sure we're not doubling up work.

**Comment by elena-kolevska** [comment]
Hey @chayim  and @dwibedis . No, I haven't gotten to `KILL` yet. Feel free to start working on it. Thanks!

**Comment by monkey92t** [comment]
`FUNCTION` is a combination of multiple commands, like `SCRIPT`.

**Comment by dwibedis** [comment]
Hi, I have raised a draft PR:- https://github.com/redis/go-redis/pull/2465/files.
Please help in checking if I am in the right direction or not,
as next step, I will have to write tests. right?

**Comment by elena-kolevska** [comment]
> Also, as I was going through other commands which were using `NewStatusCmd`, `NewTimeCmd` etc. Should I make a `FunctionCmd` struct, with function and library name as args and start using it?

Hi @dwibedis. No need to create the new structs; I'm working on them as part of the `FUNCTION LIST` implementation.
