### ISSUE TITLE
Add support for ZMPOP command

### ISSUE THREAD

**Issue by chayim** [redis/go-redis#2407]
Redis ZMPOP command was added in version 7.0.0 and is currently supported by the library. We should add support as documented [here](https://redis.io/commands/ZMPOP).

**Comment by SoulPancake** [comment]
@chayim Can I also collaborate/contribute in adding the commands if any missing, is there a road map for these things?

**Comment by chayim** [comment]
@SoulPancake totally. There's no road map (yet?)? I also need to hunt down arguments missing and the like - this was scripted.

Want it?

**Comment by SoulPancake** [comment]
@chayim Yes please!

**Comment by SoulPancake** [comment]
@chayim I have raised a PR for this https://github.com/redis/go-redis/pull/2408
and added tests too but want to be sure once if it's the right approach to take.
Might convert it to draft again if there are any style/conventions I'm breaking with this.

**Comment by SoulPancake** [comment]
I have re-opened the PR #2408 Please take a look once @chayim @monkey92t

**Comment by SoulPancake** [comment]
@monkey92t This can be closed now  https://github.com/redis/go-redis/pull/2408

**Comment by monkey92t** [comment]
> @monkey92t This can be closed now #2408

OK, thanks
