### ISSUE TITLE
Redis Streams XRead returns err = redis.Nil when it got a timeout

### ISSUE THREAD

**Issue by piavgh** [redis/go-redis#2414]
Issue tracker is used for reporting bugs and discussing new features. Please use
[stackoverflow](https://stackoverflow.com) for supporting issues.

When using the default read timeout = 3s, I got err = `redis.Nil` in the case when there is a timeout

How do I know that it's a timeout?
When I increased the timeout from 3s to 30s, I can get the data from Redis Streams successfully

## Expected Behavior

If it got a timeout, XRead should return a meaningful error to tell the consumer about that

## Current Behavior

It returns err = redis.Nil

## Possible Solution

I didn't dig into the code so I don't know if it's possible.
But I think in this case, we should return err = `ErrTimeout` so that the consumer can handle it correctly

## Steps to Reproduce

1. This is the code that I use:
```
stream := s.getStreamFromTopic(topic)

	logger.Infof("consume from stream: %v, id: %v", stream, id)

	streams, err := s.client.XRead(ctx, &redis.XReadArgs{
		Streams: []string{stream, id},
		Count:   numberOfMessages,
		Block:   s.config.ConsumeBlockDuration,
	}).Result()
	if err != nil {
		switch {
		case errors.Is(err, redis.Nil):
			logger.Error("XRead returns redis.Nil")
			return nil, nil
		default:
			return nil, err
		}
	}
```
2. Try to consume from a stream that contains a big message that will only be read in more than the read timeout (default is 3s)
3. Catch and log the error
4. See the problem

## Context (Environment)

We are using Redis Streams as a message broker to overcome the max size limit of the message in other message broker solutions (usually 2MB), because a message in our system can grow to 10MB)

**Comment by monkey92t** [comment]
`redis.Nil` is not an error, it is a state responded by redis-server.
redis-doc: `When BLOCK is used, on timeout a null reply is returned.`

**Comment by monkey92t** [comment]
I traced the network packets of redis-server, and the `XRead` command responded with "_"(ascii 95), "_" in the redis protocol represents `Nil` instead of `Error(ascii 45 "-")`

redis.doc(RESP3): "The null type is encoded just as _\r\n, which is just the underscore character followed by the CR and LF characters".

go-redis follows the data type setting of "redis-server". Timeout when `XRead` responds to `redis.Nil`.

hope this helps.

**Comment by piavgh** [comment]
Thanks, now it's clear
