### ISSUE TITLE
upgrade from github.com/go-redis/redis/v9 v9.0.0-rc.2 to github.com/redis/go-redis/v9 v9.0.2 but build failed

### ISSUE THREAD

**Issue by gzg1984** [redis/go-redis#2422]
used depend on github.com/go-redis/redis/v9 v9.0.0-rc.2,
remove go.mod and redo mod init
first of all , found this

        github.com/go-redis/redis/v9: github.com/go-redis/redis/v9@v9.0.2: parsing go.mod:
        module declares its path as: github.com/redis/go-redis/v9
                but was required as: github.com/go-redis/redis/v9

then I changed all mod dependency to github.com/redis/go-redis/v9

then I found 
```
    # github.com/redis/go-redis/v9/internal/hscan
    /root/go/pkg/mod/github.com/redis/go-redis/v9@v9.0.2/internal/hscan/structmap.go:89:23: undefined: reflect.Pointer
```
hope anybody reproduce the problem

**Comment by monkey92t** [comment]
You need to upgrade the go version, #2424

**Comment by gzg1984** [comment]
> You need to upgrade the go version, #2424

which go-redis version is compatible with go1.17.12 ?

**Comment by vmihailenco** [comment]
Replace github.com/go-redis/redis/v9 with github.com/redis/go-redis/v9 - https://uptrace.dev/blog/go-redis-v9.html
