### ISSUE TITLE
go.mod is on Go 1.17, but internal function references type renamed/added in Go 1.18

### ISSUE THREAD

**Issue by LCaparelli** [redis/go-redis#2424]
## Expected Behavior

I'm able to build code that uses go-redis as a dependency using go v1.17

## Current Behavior

```
❯ go version
go version go1.17.2 linux/amd64
❯ go build
# github.com/redis/go-redis/v9/internal/hscan
../../.gvm/pkgsets/go1.17.2/global/pkg/mod/github.com/redis/go-redis/v9@v9.0.2/internal/hscan/structmap.go:89:23: undefined: reflect.Pointer
```

## Possible Solution

I'm assuming that this is because `reflect.Ptr` was renamed to `reflect.Pointer` in Go 1.18. From the [release notes](https://tip.golang.org/doc/go1.18):

> [reflect.Ptr](https://tip.golang.org/pkg/reflect#Ptr) and [reflect.PtrTo](https://tip.golang.org/pkg/reflect#PtrTo) have been renamed to [reflect.Pointer](https://tip.golang.org/pkg/reflect#Pointer) and [reflect.PointerTo](https://tip.golang.org/pkg/reflect#PointerTo), respectively, for consistency with the rest of the reflect package. The old names will continue to work, but will be deprecated in a future Go release.

We're currently on 1.17 according to go.mod:

https://github.com/redis/go-redis/blob/a38f75b640398bd709ee46c778a23e80e09d48b5/go.mod#L3

But we're using the renamed type from 1.18:

https://github.com/redis/go-redis/blob/a38f75b640398bd709ee46c778a23e80e09d48b5/internal/hscan/structmap.go#L89

## Steps to Reproduce

1. use Go 1.17
2. import `"github.com/redis/go-redis/v9"`
3. run `go build`

## Context (Environment)

Trying to use the client to communicate with Redis on project using Go 1.17.

## Detailed Description

Not much to add I think, but please let me know if I could elaborate further on something specific.

## Possible Implementation

My suggestion would be to continue to use `reflect.Ptr` until we upgrade to go 1.18. Continuing to use `reflect.Ptr` even after that might still be desirable to prevent compatibility issues. Not sure there are specific policies regarding how this lib handles this kind of things, just spitballing with limited context, so take it with a grain of salt.

**Comment by LCaparelli** [comment]
Upgraded my own project to 1.18 to work around this, works fine so far.

**Comment by vmihailenco** [comment]
@LCaparelli could you send a PR that bumps Go version to 1.18?

**Comment by LCaparelli** [comment]
@vmihailenco ack, no problem! Should we continue to use `reflect.Pointer` then?
