### ISSUE TITLE
redisotel with opentelemetry new tag

### ISSUE THREAD

**Issue by zhanjunjie2019** [redis/go-redis#2435]
command : go mod tidy
result:
        github.com/go-redis/redis/extra/redisotel/v9 imports
        go.opentelemetry.io/otel/metric/instrument/syncfloat64: module go.opentelemetry.io/otel/metric@latest found (v0.36.0), but does not contain package go.opentelemetry.io/otel/metric/instrument/syncfloat64

Sorry, my English is not good.

**Comment by vmihailenco** [comment]
Try to run `go get -u` to update to the latest version. This should be already fixed in 9.0.2
