### ISSUE TITLE
go 17.2 undefined: reflect.Pointer

### ISSUE THREAD

**Issue by fanybook** [redis/go-redis#2452]
env: go 17.2
error: # github.com/redis/go-redis/v9/internal/hscan
../../../go/pkg/mod/github.com/redis/go-redis/v9@v9.0.2/internal/hscan/structmap.go:89:23: undefined: reflect.Pointer

template
=======================================================
[stackoverflow](https://stackoverflow.com) for supporting issues.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by monkey92t** [comment]
go-redis requires go1.18 or above.
