### ISSUE TITLE
NOAUTH Authentication required when use go-redis connect dragonfly

### ISSUE THREAD

**Issue by ly269nva** [redis/go-redis#2462]
i want use go-redis/v9  to connect dragonfly (redis_version:df-v0.15.0, a db like redis), but i go a err : NOAUTH Authentication required.
but it ok when i use  go-redis/v9 to connect my local redis, 
and it also ok when i use go-redis/v8 to connect dragonfly.
this is a bug?  why go-redis/v9 not support dragonfly with password?
`
var redisdb *redis.Client  

 redisdb = redis.NewClient(&redis.Options{  
      Addr:     "127.0.0.1:6379", // 指定
      Password: "1234",
      DB:       2, // redis一共16个库，指定其中一个库即可
      PoolSize: 2000,
 })    

t.Log(redisdb.Info(context.Background()))
`

**Comment by monkey92t** [comment]
I don't know the `dragonfly` system, let me introduce the difference between go-redis v8 and v9:

v8: 
```go
if c.opt.Password != "" {
	if c.opt.Username != "" {
		pipe.AuthACL(ctx, c.opt.Username, c.opt.Password)
	} else {
		pipe.Auth(ctx, c.opt.Password)
	}
}
```

v9 first uses the `HELLO username password` command for authentication, and if it fails, then use the authentication method of the v8 version.

**Comment by monkey92t** [comment]
If there are no more questions, we close this issue.
