### ISSUE TITLE
Write Command Sometimes Directed To Read Only Slave Node in ClusterClient

### ISSUE THREAD

**Issue by Decoydoll** [redis/go-redis#2468]
To utilize our read only replica node in Aiven, we follow the example in [here](https://github.com/redis/go-redis/blob/master/example_test.go#L81) to create a cluster client with just one slot, with one master node and one read only slave node. But, when we deployed it, it randomly gets error `READONLY You can't write against a read only replica.` which we assume it sometimes tried to do write operation to the read only slave node.

From what i understand from the code [here](https://github.com/redis/go-redis/blob/73d939e7bfad9168da6f9d834436d29205889d62/cluster.go#L1799-L1802), only master node can do both read and write operations, where the slave can only do read operation if the ReadOnly toggle is on, CMIIW.

## Expected Behavior

No write command run against the read only slave node

## Current Behavior

Sometimes write command run against the read only slave node

## Steps to Reproduce
```go
clusterSlots := func(ctx context.Context) ([]redis.ClusterSlot, error) {
		slots := []redis.ClusterSlot{
			{
				Start: 0,
				End:   8191,
				Nodes: []redis.ClusterNode{{
					Addr: ":7000", // master
				}, {
					Addr: ":8000", // slave, read-only
				}},
			}
		}
		return slots, nil
	}

	rdb := redis.NewClusterClient(&redis.ClusterOptions{
		ClusterSlots:  clusterSlots,
		RouteRandomly: true,
	})

         for i := 0; i < 100; i++ {
		err	:= rdb.Set(context.Background(), "foo", "bar", time.Second)
		fmt.Println(err) // sometimes it returns error `READONLY You can't write against a read only replica.`
	}
 
```

**Comment by monkey92t** [comment]
In redis-cluster mode, the key distribution range is [0-16383], in your example only [0-8191] is set, if hash(key) % 16384 > 8191, go-redis will use random nodes.

**Comment by monkey92t** [comment]
exp:

```go
slots := []redis.ClusterSlot{
			// First node with 1 master and 1 slave.
			{
				Start: 0,
				End:   8191,
				Nodes: []redis.ClusterNode{{
					Addr: ":7000", // master
				}, {
					Addr: ":8000", // 1st slave
				}},
			},
			// Second node with 1 master and 1 slave.
			{
				Start: 8192,
				End:   16383,
				Nodes: []redis.ClusterNode{{
					Addr: ":7001", // master
				}, {
					Addr: ":8001", // 1st slave
				}},
			},
		}
```

**Comment by Decoydoll** [comment]
Thank you for the explaination, it solved the issue!
