### ISSUE TITLE
XClaim does not work as expected

### ISSUE THREAD

**Issue by piavgh** [redis/go-redis#2514]
Issue tracker is used for reporting bugs and discussing new features. Please use
[stackoverflow](https://stackoverflow.com) for supporting issues.

## Expected Behavior

The XClaim method should return the list of claimed messages (XMessages) (as specified in the document https://redis.io/commands/xclaim/ Return section), and err = nil in case of success event

## Current Behavior

- It claim the messages successfully (I checked RedisInsight and I see that the messages were claimed)
![image](https://user-images.githubusercontent.com/4060207/229102095-7f5c8105-7c1a-4f98-871f-43595085229a.png)

- The returned XMessages is nil, while the err = redis: nil
![image](https://user-images.githubusercontent.com/4060207/229102414-a05b5de0-868b-4678-adc5-9dcfd7d85b66.png)

## Steps to Reproduce

1. 
```
xMessages, err := s.client.XClaim(ctx, &redis.XClaimArgs{
		Stream:  "stream-name",
		Group:    "consumer-group-name",
		Consumer: "consumer-name",
		MinIdle:  30 * time.Second,
		Messages: <list of messages>,
	}).Result()
	if err != nil {
		return nil, err // <= it will run into this section
	}
 
        ...
```
2.
3.
4.

## Context (Environment)

I'm trying to use `XPendingExt` and `XClaim` to set up a workflow that if one consumer dies unexpectedly, another consumer can take the unprocessed messages and continue to process them (so that no messages are loss without being processed)

**Comment by monkey92t** [comment]
example:

```go
	ctx := context.Background()
	client := redis.NewClient(&redis.Options{
		Addr: ":6379",
	})

	_, err := client.Pipelined(ctx, func(pipe redis.Pipeliner) error {
		client.Del(ctx, "stream-name")

		client.XAdd(ctx, &redis.XAddArgs{
			Stream: "stream-name",
			ID:     "1-0",
			Values: map[string]interface{}{"a-1": "a-2"},
		})
		client.XAdd(ctx, &redis.XAddArgs{
			Stream: "stream-name",
			ID:     "2-0",
			Values: []interface{}{"b-1", "b-2"},
		})
		client.XAdd(ctx, &redis.XAddArgs{
			Stream: "stream-name",
			ID:     "3-0",
			Values: []string{"c-1", "c-2"},
		})
		return nil
	})
	if err != nil {
		log.Fatal(err)
	}

	if err = client.XGroupCreate(ctx, "stream-name", "consumer-group-name", "0").Err(); err != nil {
		log.Fatal(err)
	}

	res, err := client.XReadGroup(ctx, &redis.XReadGroupArgs{
		Group:    "consumer-group-name",
		Consumer: "consumer-name",
		Streams:  []string{"stream-name", ">"},
		Count:    2,
	}).Result()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("x read group:", res)
        // x read group: [{stream-name [{1-0 map[a-1:a-2]} {2-0 map[b-1:b-2]}]}]

	// no ack

	time.Sleep(4 * time.Second)
	
	msgs, err := client.XClaim(ctx, &redis.XClaimArgs{
		Stream:   "stream-name",
		Group:    "consumer-group-name",
		Consumer: "consumer-name",
		MinIdle:  3 * time.Second,
		Messages: []string{"1-0", "2-0", "3-0"},
	}).Result()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("xClaim messages:", msgs)
        // xClaim messages: [{1-0 map[a-1:a-2]} {2-0 map[b-1:b-2]}]
```

**Comment by monkey92t** [comment]
Please note that we paused for 4 seconds in the middle because we set the MinIdle to 3 seconds in our example.

**Comment by piavgh** [comment]
> Please note that we paused for 4 seconds in the middle because we set the MinIdle to 3 seconds in our example.

What do you mean?

**Comment by monkey92t** [comment]
> > Please note that we paused for 4 seconds in the middle because we set the MinIdle to 3 seconds in our example.
> 
> What do you mean?

## redis-doc:

Note that the message is claimed only if its idle time is greater than the minimum idle time we specify when calling XCLAIM. Because as a side effect XCLAIM will also reset the idle time (since this is a new attempt at processing the message), two consumers trying to claim a message at the same time will never both succeed: only one will successfully claim the message. This avoids that we process a given message multiple times in a trivial way (yet multiple processing is possible and unavoidable in the general case).

**Comment by monkey92t** [comment]
In you example:

```go
&redis.XClaimArgs{
	Stream:  "stream-name",
	Group:    "consumer-group-name",
	Consumer: "consumer-name",
	MinIdle:  30 * time.Second,
	Messages: <list of messages>,
}
```
MinIdle = 30s

We need to wait for more than 30 seconds for xclaim to get the result.

**Comment by piavgh** [comment]
@monkey92t : no, you misunderstand my problem.

At the beginning, consumer A (`worker-6f7e...` in my image) takes 10 messages and stuck => 10 messages are in the pending list of consumer A

After that, consumer B (`worker-cda2...` in my image`) can claim 10 messages successfully (in my 1st image), but the returned xMessages = nil.
It should return 10 messages in an array

Please reopen this issue

**Comment by piavgh** [comment]
I will try to use go-redis v9 to see if the issue persists. At the moment, I'm using go-redis v8

**Comment by monkey92t** [comment]
I still don't understand your question. Could you provide a complete example?

**Comment by piavgh** [comment]
Let me try to record a video with Goland debugger and RedisInsight. I will try to explain the problem in more detail.

**Comment by piavgh** [comment]
@monkey92t : please check this video https://screenpal.com/watch/c0fVXfVar45

I'm using go-redis v9.0.2 (latest version) in the video.

Because the code is quite complex and also it's my company asset so it's not easy to create a complete example

**Comment by monkey92t** [comment]
My example:

STEP-1: I have created three messages and a stream group.

STEP-2: consumer `consumer-name-1` read 3 messages. val: `1-0, 2-0, 3-0`

STEP-3: sleep 4s, suppose `consumer-name-1` is down.

STEP-4: Use the `XPending` command to check no-xack messages. get: `1-0....3-0`

STEP-5: Use the XClaim command to claim message 1-0, new consumer: `consumer-name-2`

STEP-6: `consumer-name-2` successfully processed the message and sent an xack command.

STEP-7: Message 1-0 has been processed, remaining messages 2-0 and 3-0.

```go
func main() {
	ctx := context.Background()
	client := redis.NewClient(&redis.Options{
		Addr: ":6379",
	})

	// STEP-1
	_, err := client.Pipelined(ctx, func(pipe redis.Pipeliner) error {
		pipe.Del(ctx, "stream-name")

		pipe.XAdd(ctx, &redis.XAddArgs{
			Stream: "stream-name",
			ID:     "1-0",
			Values: map[string]interface{}{"a-1": "a-2"},
		})
		pipe.XAdd(ctx, &redis.XAddArgs{
			Stream: "stream-name",
			ID:     "2-0",
			Values: []interface{}{"b-1", "b-2"},
		})
		pipe.XAdd(ctx, &redis.XAddArgs{
			Stream: "stream-name",
			ID:     "3-0",
			Values: []string{"c-1", "c-2"},
		})
		pipe.XGroupCreate(ctx, "stream-name", "consumer-group-name", "0")

		return nil
	})
	if err != nil {
		log.Fatal(err)
	}

	// ---------------------------------------------------------------

	// STEP-2
	res, err := client.XReadGroup(ctx, &redis.XReadGroupArgs{
		Group:    "consumer-group-name",
		Consumer: "consumer-name-1",
		Streams:  []string{"stream-name", ">"},
		Count:    3,
	}).Result()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("xReadGroup:", res)
	// xReadGroup: [{stream-name [{1-0 map[a-1:a-2]} {2-0 map[b-1:b-2]} {3-0 map[c-1:c-2]}]}]

	// ---------------------------------------------------

	// no ack

	// STEP-3
	time.Sleep(4 * time.Second)

	// ---------------------------------------------------

	// STEP-4
	pending, err := client.XPending(ctx, "stream-name", "consumer-group-name").Result()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("xPending: %+v\n", pending)
	// xPending: &{Count:3 Lower:1-0 Higher:3-0 Consumers:map[consumer-name-1:3]}

	// ---------------------------------------------------

	// STEP-5
	msgs, err := client.XClaim(ctx, &redis.XClaimArgs{
		Stream:   "stream-name",
		Group:    "consumer-group-name",
		Consumer: "consumer-name-2",
		MinIdle:  3 * time.Second,
		Messages: []string{pending.Lower},
	}).Result()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("xClaimMessages:", msgs)
	// xClaimMessages: [{1-0 map[a-1:a-2]}]

	// ---------------------------------------------------

	// STEP-6
	err = client.XAck(ctx, "stream-name", "consumer-group-name", pending.Lower).Err()
	if err != nil {
		log.Fatal(err)
	}

	// ---------------------------------------------------

	// STEP-7
	pending, err = client.XPending(ctx, "stream-name", "consumer-group-name").Result()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("xPending: %+v\n", pending)
	// xPending: &{Count:2 Lower:2-0 Higher:3-0 Consumers:map[consumer-name-1:2]}
}
```

**Comment by monkey92t** [comment]
> @monkey92t : please check this video https://screenpal.com/watch/c0fVXfVar45
> 
> I'm using go-redis v9.0.2 (latest version) in the video.
> 
> Because the code is quite complex and also it's my company asset so it's not easy to create a complete example

I watched your video, but I didn't see the code for many functions. I suspect that in your video, the stream message has already been processed. You can use go-redis-hook to print all executed Redis commands.

example:

output:
```go
redis command: [del stream-name]
redis command: [xadd stream-name 1-0 a-1 a-2]
redis command: [xadd stream-name 2-0 b-1 b-2]
redis command: [xadd stream-name 3-0 c-1 c-2]
redis command: [xgroup create stream-name consumer-group-name 0]
redis command: [xreadgroup group consumer-group-name consumer-name-1 count 3 block 0 streams stream-name >]
redis command: [xpending stream-name consumer-group-name]
redis command: [xclaim stream-name consumer-group-name consumer-name-2 3000 0-0]
redis command: [xack stream-name consumer-group-name 1-0]
```

```go
package main

import (
	"context"
	"fmt"
	"log"
	"net"
	"time"

	"github.com/redis/go-redis/v9"
)

type hook struct{}

func (h *hook) DialHook(next redis.DialHook) redis.DialHook {
	return func(ctx context.Context, network, addr string) (net.Conn, error) {
		return next(ctx, network, addr)
	}
}

func (h *hook) ProcessHook(next redis.ProcessHook) redis.ProcessHook {
	return func(ctx context.Context, cmd redis.Cmder) error {
		fmt.Println("redis command:", cmd.Args())
		return next(ctx, cmd)
	}
}
func (h *hook) ProcessPipelineHook(next redis.ProcessPipelineHook) redis.ProcessPipelineHook {
	return func(ctx context.Context, cmds []redis.Cmder) error {
		for _, v := range cmds {
			fmt.Println("redis command:", v.Args())
		}
		return next(ctx, cmds)
	}
}

func main() {
	ctx := context.Background()
	client := redis.NewClient(&redis.Options{
		Addr: ":6379",
	})

	client.AddHook(&hook{})

	// STEP-1
	_, err := client.Pipelined(ctx, func(pipe redis.Pipeliner) error {
		pipe.Del(ctx, "stream-name")

		pipe.XAdd(ctx, &redis.XAddArgs{
			Stream: "stream-name",
			ID:     "1-0",
			Values: map[string]interface{}{"a-1": "a-2"},
		})
		pipe.XAdd(ctx, &redis.XAddArgs{
			Stream: "stream-name",
			ID:     "2-0",
			Values: []interface{}{"b-1", "b-2"},
		})
		pipe.XAdd(ctx, &redis.XAddArgs{
			Stream: "stream-name",
			ID:     "3-0",
			Values: []string{"c-1", "c-2"},
		})
		pipe.XGroupCreate(ctx, "stream-name", "consumer-group-name", "0")

		return nil
	})
	if err != nil {
		log.Fatal(err)
	}

	// ---------------------------------------------------------------

	// STEP-2
	res, err := client.XReadGroup(ctx, &redis.XReadGroupArgs{
		Group:    "consumer-group-name",
		Consumer: "consumer-name-1",
		Streams:  []string{"stream-name", ">"},
		Count:    3,
	}).Result()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("xReadGroup:", res)
	// xReadGroup: [{stream-name [{1-0 map[a-1:a-2]} {2-0 map[b-1:b-2]} {3-0 map[c-1:c-2]}]}]

	// ---------------------------------------------------

	// no ack

	// STEP-3
	time.Sleep(4 * time.Second)

	// ---------------------------------------------------

	// STEP-4
	pending, err := client.XPending(ctx, "stream-name", "consumer-group-name").Result()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("xPending: %+v\n", pending)
	// xPending: &{Count:3 Lower:1-0 Higher:3-0 Consumers:map[consumer-name-1:3]}

	// ---------------------------------------------------

	// STEP-5
	msgs, err := client.XClaim(ctx, &redis.XClaimArgs{
		Stream:   "stream-name",
		Group:    "consumer-group-name",
		Consumer: "consumer-name-2",
		MinIdle:  3 * time.Second,
		Messages: []string{"0-0"},
	}).Result()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("xClaimMessages:", msgs)
	// xClaimMessages: [{1-0 map[a-1:a-2]}]

	// ---------------------------------------------------

	// STEP-6
	err = client.XAck(ctx, "stream-name", "consumer-group-name", pending.Lower).Err()
	if err != nil {
		log.Fatal(err)
	}

	// ---------------------------------------------------

	// STEP-7
	pending, err = client.XPending(ctx, "stream-name", "consumer-group-name").Result()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("xPending: %+v\n", pending)
	// xPending: &{Count:2 Lower:2-0 Higher:3-0 Consumers:map[consumer-name-1:2]}
}
```

**Comment by monkey92t** [comment]
@piavgh At the end of your video, there were already new consumers taking over the message, so I suspect you repeated the execution of XClaim when handling the messages.

**Comment by monkey92t** [comment]
I haven't found any further evidence indicating that there's a problem with go-redis. 

/cc @vmihailenco  What's your opinion?

**Comment by piavgh** [comment]
> @piavgh At the end of your video, there were already new consumers taking over the message, so I suspect you repeated the execution of XClaim when handling the messages.

No, each worker is 1 consumer only and I don't have any other goroutine that does the claim tasks.

```
there were already new consumers taking over the message
```
It is the instance of worker that I ran in debugging mode. It claimed the messages successfully but somehow the returned `xMessages` is nil and `err` is `redis: nil` (that's what I was trying to explain in the first comment 😄 )

Anyway, I will try to use your example code with my existing stream `ethereum:tasks` to see if the issue persists. Maybe it's from Redis (I'm using Redis v6 docker image).
But it's night time for me now so I will reply tomorrow.

Btw, thank you for your example, it makes it easier to test the code

**Comment by monkey92t** [comment]
> But it's night time for me now so I will reply tomorrow.

ok, no problem~

It seems that we are in the same time zone, and it is also nighttime here for me, you singapore?  :)

**Comment by piavgh** [comment]
@monkey92t : I'm trying to run a simple example today and this is the result: https://screenpal.com/watch/c0fnjyVa35C

Luckily I can reproduce the issue using your sample code.

I'm trying to export the STREAM `ethereum:tasks` in case you need to reproduce it in your localhost, but at the moment I can't find how to do it on Google. If you know how to export the STREAM to a file, please tell me.

Btw, I'm from Vietnam 😄 Are you from Singapore?

**Comment by piavgh** [comment]
I tried to use `telnet` to `localhost 6379`, and it looks like Redis itself does not return the data I want. This is very weird

My case:
<img width="1107" alt="Screenshot 2023-04-02 at 4 12 11 PM" src="https://user-images.githubusercontent.com/4060207/229343621-8148c74c-5875-4e79-a3df-05d9cad9c97e.png">

Your example:
<img width="892" alt="Screenshot 2023-04-02 at 4 07 45 PM" src="https://user-images.githubusercontent.com/4060207/229343659-469920f2-5bc3-425f-8d21-338683f5254e.png">

**Comment by monkey92t** [comment]
@piavgh You redis env?
redis-server(single node)? cluster? sentinel?   and redis-server version?

**Comment by piavgh** [comment]
<img width="1049" alt="Screenshot 2023-04-02 at 5 26 37 PM" src="https://user-images.githubusercontent.com/4060207/229347388-a1b2ccbe-ed70-42f6-957d-85b87ad05bfb.png">

=> Redis server v=6.2.5

--- 
This is my whole docker-compose.yaml file:

```
version: '3.1'

services:
  redis:
    image: redis
    container_name: redis-pool-service-master
    ports:
      - "6379:6379"
    networks:
      - redis-cluster

  redis-slave:
    image: redis
    container_name: redis-pool-service-slave
    ports:
      - "6380:6379"
    command: redis-server --slaveof redis 6379
    depends_on:
      - redis
    networks:
      - redis-cluster

  redis-sentinel:
    image: 'bitnami/redis-sentinel'
    depends_on:
      - redis
      - redis-slave
    environment:
      - REDIS_MASTER_HOST=redis
    ports:
      - '26379-26381:26379'
    networks:
      - redis-cluster

  datadog:
    container_name: dd-agent
    image: gcr.io/datadoghq/agent:7
    restart: always
    ports:
      - "8125:8125/udp"
      - "8126:8126"
    environment:
      - DD_API_KEY="<enter_datadog_api_key_here>"
      - DD_SITE=datadoghq.com
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
      # exclude all containers from autodiscovery
      # track only below containers
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      # - /opt/dd-agent/run:/opt/dd-agent/run:rw
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

networks:
  redis-cluster:
    driver: bridge
```

But when running Redis, I run only `docker compose up -d redis`, so it should be a `single node` only

**Comment by piavgh** [comment]
[dump.rdb.zip](https://github.com/redis/go-redis/files/11131840/dump.rdb.zip)
@monkey92t : anw, this is the dump file of my Redis data in case you want to try to reproduce this issue
Thanks a lot for your time (especially this is the weekend)

**Comment by monkey92t** [comment]
@piavgh  

Hi, I downloaded your DUMP file and imported it into my redis-server(v7.0.8), but there seems to be an issue with your data. 

The messages obtained through XCLAIM are no longer present in the stream. I'm not sure why they are missing, but it's possible that you may have deleted them using XDEL. 

Here's an explanation for resolving this issue:

```shell
127.0.0.1:6379> xpending ethereum:tasks pool-state-updater-group
1) (integer) 36
2) "1680254034252-0"
3) "1680254065899-0"
4) 1) 1) "worker-2cd4383d-512d-47db-97e6-fe0b1ffa087b"
      2) "6"
   2) 1) "worker-35c7e4a1-2b81-408f-b6fd-03202d6d3a18"
      2) "8"
   3) 1) "worker-9d13c39c-6372-4e62-8e33-ff02f7325be2"
      2) "14"
   4) 1) "worker-dad496a7-1aa8-46c2-bf7c-3d85b58df048"
      2) "8"
```
I first executed the XPENDING command, which returned a response with the message-id 1680254034252-0. 
However, this message does not exist in the STREAM:

```shell
127.0.0.1:6379> xread count 1 STREAMS ethereum:tasks 1680254034251-0
1) 1) "ethereum:tasks"
   2) 1) 1) "1680254034274-0"
         2) 1) "task"
            2) "{\"type\":2,\"poolAddress\":\"0x80b044ba2cd812d49fae1bf97cbdb06aec4536d0\"}"
```
I did not receive the expected message-id 1680254034252-0, but instead unexpectedly received 1680254034274-0. This indicates that message-id 1680254034252-0 does not exist.
It's possible that during your testing process, you accidentally deleted it using the XDEL command.

Therefore, you are not getting any results using the XCLAIM command because the Redis server has removed it.

## redis-doc
XCLAIM will not claim a message in the following cases:

The message doesn't exist in the group PEL (i.e. it was never read by any consumer)
The message exists in the group PEL but not in the stream itself (i.e. the message was read but never acknowledged, and then was deleted from the stream, either by trimming or by [XDEL](https://redis.io/commands/xdel))

**Comment by piavgh** [comment]
@monkey92t :

> It's possible that during your testing process, you accidentally deleted it using the XDEL command.

Thanks to this insight, now I think I understand why it has this weird behavior

In my CleanUpTasks, I do 3 things:
- Filter to get all messages that were delivered more than 10 times and put them into an array to send to the "dead letter queue" stream
- Publish these DLQ messages to the dead letter queue stream
- **Delete those messages using XDel** because now they are not necessary inside the "tasks" stream anymore

> - **Delete those messages using XDel**
This action is what caused the weird behavior

Because the messages were deleted, but they still exist in the pending list of a consumer, so when another consumer tries to claim it, it will be not found.

---

Just a question: Is it true that a better way to handle this "clean up tasks" thing is just ACK the message instead of deleting it?

**Comment by monkey92t** [comment]
> Just a question: Is it true that a better way to handle this "clean up tasks" thing is just ACK the message instead of deleting it?

It depends on what your goal is. Only use the XDEL/XTRIM command to remove messages when you are sure that the messages will never be used again. 

If your STREAMS are used by multiple groups, deleting STREAMS messages will affect other groups. You can consider other commands, such as XACK that you mentioned, or XGROUP DELCONSUMER.

Removing messages from STREAMS should be done very carefully and only when you are certain that the messages are no longer being used anywhere, including by groups, xread, xrange, consumers, or any other applications. 

This is because the design principle of STREAMS is for multiple processes to share the reading of messages, and messages should not be removed from STREAMS simply because a consumer has already consumed them.

**Comment by piavgh** [comment]
> > Just a question: Is it true that a better way to handle this "clean up tasks" thing is just ACK the message instead of deleting it?
> 
> It depends on what your goal is. Only use the XDEL/XTRIM command to remove messages when you are sure that the messages will never be used again.
> 
> If your STREAMS are used by multiple groups, deleting STREAMS messages will affect other groups. You can consider other commands, such as XACK that you mentioned, or XGROUP DELCONSUMER.
> 
> Removing messages from STREAMS should be done very carefully and only when you are certain that the messages are no longer being used anywhere, including by groups, xread, xrange, consumers, or any other applications.
> 
> This is because the design principle of STREAMS is for multiple processes to share the reading of messages, and messages should not be removed from STREAMS simply because a consumer has already consumed them.

Thanks again.
After this weekend, I think I understand a lot more about Redis Stream 😄
