### ISSUE TITLE
Naming inconsistency: FCallRo vs EvalRO, EvalShaRO, SortRO

### ISSUE THREAD

**Issue by alex9801** [redis/go-redis#2545]
Support for [FCALL_RO](https://redis.io/commands/fcall_ro/) command was added in [version 9.0.3](https://github.com/redis/go-redis/releases/tag/v9.0.3) with the name `FCallRo()`.
https://pkg.go.dev/github.com/redis/go-redis/v9@v9.0.3#Client.FCallRo

However, other read-only commands are named with `~RO()` convention. (e.g. `EvalRO()`, `EvalShaRO()`, `SortRO()`)
https://pkg.go.dev/github.com/redis/go-redis/v9@v9.0.3#Client.EvalRO
https://pkg.go.dev/github.com/redis/go-redis/v9@v9.0.3#Client.EvalShaRO
https://pkg.go.dev/github.com/redis/go-redis/v9@v9.0.3#Client.SortRO

The slight naming inconsistency here could be surprising to users, especially for people migrating their code from using EVAL(SHA)_RO to FCALL_RO.

One possible solution could be adding `FCallRO()` and deprecating `FCallRo()`.

**Comment by monkey92t** [comment]
Yes, you are right, it is short for ReadOnly, we should name it `RO` instead of `Ro`, we ignore this...

But according to `go mod` specifications, we should maintain compatibility with 9.0.3, we can consider adding a new API, such as `FCallRO`, and mark FCallRo as deprecated.
