### ISSUE TITLE
Could you please refrain from printing any output to stdout and stderr

### ISSUE THREAD

**Issue by SURA907** [redis/go-redis#2555]
## version
v9.0.2

## describe
Hello, I introduced go-redis when developing Git server-side hooks, and it works very great!
Git server-side hooks have a feature - all stdout and stderr are sent remotely to the client
When i use sentinel mode, the information printed by go-redis on stderr is sent directly to the client
```
$ git push origin master:sura-008
> remote: Powered by xxxx
> remote: redis: 2023/04/20 15:28:42 sentinel.go:685: sentinel: new master="mymaster" addr="127.0.0.1:6000"
> remote: all works done!
> To localhost:sura/redis-sentinel-001.git
> * [new branch]      master -> sura-008
```
This is a nightmare. As a library, can we keep quiet by default?

**Comment by ktsivkov** [comment]
Hello @SURA907,
First I note that I am speaking as a community "member", not behalf of the redis org.

Your purposal makes sense but as it will take time to be implemented and changed, I have a solution for you.

There's a method called SetLogger func, that you can use to introduce your own logging service. 
That logger must implement the following interface
```go
type Logging interface {
	Printf(ctx context.Context, format string, v ...interface{})
}

// Example

type customLogger struct {
}

func (l customLogger ) Printf(ctx context.Context, format string, v ...interface{}) {

}

redis.SetLogger(&logger{})
```

Cheers!

**Comment by SURA907** [comment]
> Hello @SURA907, First I note that I am speaking as a community "member", not behalf of the redis org.
> 
> Your purposal kinda makes sense. From the one side, having error output by default will hide the expected feedback for many users, and make it harder to debug if anything goes wrong. Usually all libraries have some way to give you instant feedback. On the other hand, it'd make sense to be easily disabled, but as it will take time to be implemented and changed, I have a solution for you.
> 
> There's a func called SetLogger, that you can use to introduce your own logging service. That logger must implement the following interface
> 
> ```go
> type Logging interface {
> 	Printf(ctx context.Context, format string, v ...interface{})
> }
> 
> // Example
> 
> type customLogger struct {
> }
> 
> func (l customLogger ) Printf(ctx context.Context, format string, v ...interface{}) {
> 
> }
> 
> redis.SetLogger(&logger{})
> ```
> 
> Cheers!

Thank u very much, this is indeed helpful. I also did the same treatment after discovering this situation.
I open this issue hoping that go-redis can prevent this behavior or at least tell me why
