### ISSUE TITLE
cannot use labels (variable of type []"go.opentelemetry.io/otel/attribute".KeyValue) as []metric.ObserveOption value in argument to o.ObserveInt64

### ISSUE THREAD

**Issue by alidehghan** [redis/go-redis#2571]
I just install v9 redis and extra to hook on jaeger, but encounter this error when I wanted to run the project.

## Expected Behavior

no error shown

## Current Behavior

has many error like this:

`/home/ali/go/pkg/mod/github.com/redis/go-redis/extra/redisotel/v9@v9.0.2/metrics.go:135:59: cannot use labels (variable of type []"go.opentelemetry.io/otel/attribute".KeyValue) as []metric.ObserveOption value in argument to o.ObserveInt64

/home/ali/go/pkg/mod/github.com/redis/go-redis/extra/redisotel/v9@v9.0.2/metrics.go:136:59: cannot use labels (variable of type []"go.opentelemetry.io/otel/attribute".KeyValue) as []metric.ObserveOption value in argument to o.ObserveInt64

/home/ali/go/pkg/mod/github.com/redis/go-redis/extra/redisotel/v9@v9.0.2/metrics.go:137:56: cannot use labels (variable of type []"go.opentelemetry.io/otel/attribute".KeyValue) as []metric.ObserveOption value in argument to o.ObserveInt64`

**Comment by vmihailenco** [comment]
This was fixed by https://github.com/redis/go-redis/pull/2569. Should eb released in v9.0.4
