### ISSUE TITLE
go get install fails with bad module file path

### ISSUE THREAD

**Issue by jwatte** [redis/go-redis#2582]
Using go 1.19

Running:

  $ go get github.com/go-redis/redis/v9@latest 

getting error:

  go: github.com/go-redis/redis/v9@v9.0.4: parsing go.mod:
	module declares its path as: github.com/redis/go-redis/v9
	        but was required as: github.com/go-redis/redis/v9

And this is indeed correct -- the go.mod has the wrong path:

  module github.com/redis/go-redis/v9

**Comment by vmihailenco** [comment]
Use `go get github.com/redis/go-redis/v9@latest`
