### ISSUE TITLE
Clients should identify themselves on connect

### ISSUE THREAD

**Issue by chayim** [redis/go-redis#2654]
[CLIENT SETINFO](https://redis.io/commands/client-setinfo/) is a new fire-and-forget command that is available as part of redis 7.2. Clients should send the lowercased version of the client name (i.e redis-py, jedis, go-redis) as part of the initial connect, after authenticating to the server.

**Comment by SoulPancake** [comment]
Would like to work on this @chayim

**Comment by rueian** [comment]
Hi @chayim,

Should clients always send their own name to the server or should clients let users decide what value to send?

**Comment by chayim** [comment]
@rueian Clients should send their own name *and* their current version - notice the arguments. There will, of course be versions of redis (prior to 7.2) that don't support this. So, the general idea is to send always, and fail silently when not supported by the redis server.

I'm a fan of fire and forget, versus check version then fire.
