### ISSUE TITLE
Update CLIENT-SETINFO to support suffixes

### ISSUE THREAD

**Issue by chayim** [redis/go-redis#2707]
CLIENT SETINFO should be extended to support community members inserting their own suffixes, for Redis usage.

1. Clients should by default set-lib during connect with their name and version.
2. Clients should allow users to not send this
3. We should allow a user do send a suffix to the LIB-NAME portion - this allows us to learn about how things are used.
4. Our clients continue to send their version upstream for LIB-VER

Strings should have the client name, and an optional suffix. They should be formatted ClientName(<suffix>). For example:

1. If you're NRedisStack - LIB-NAME: NRedisStack(StackExchange.Redis-v2.6.8;.NET-6.2.18) LIB-VERSION: 0.9.1
2. If you're a project using NRedisStack (say SemtanticKernel): LIB-NAME (NRedisStack(SemanticKernel-v0.1.7;.NET-6.2.18) LIB-VERSION: 0.9.1

Considerations:
1. Users should not send brackets, or braces, and we should error accordingly.
2. We should replace spaces a user sends with hyphens

**Comment by SoulPancake** [comment]
Can I take this up? @chayim

**Comment by chayim** [comment]
@SoulPancake apologies, didn't see this and @ofekshenawa had pushed a bunch of things. I am so so sorry :(

@ofekshenawa I'll leave this to you
