### ISSUE TITLE
`Cmdable` does not include `BitMapCmdable`

### ISSUE THREAD

**Issue by sethrylan** [redis/go-redis#2736]
Issue tracker is used for reporting bugs and discussing new features. Please use
[stackoverflow](https://stackoverflow.com) for supporting issues.

## Expected Behavior

`Cmdable` should have the `GetBit()` method.

## Current Behavior

```
type redis.Cmdable has no field or method GetBit
```

## Possible Solution

Add `BitMapCmdable` to the `Cmdable` interface.

This issue (and fix) are very similar to https://github.com/redis/go-redis/issues/2723

**Comment by fkollmann** [comment]
any update? started locking the version to v9.1 for all our projects...
