### ISSUE TITLE
[Feature request] HSet struct with pointer

### ISSUE THREAD

**Issue by numberinho** [redis/go-redis#2745]
### Discussed in https://github.com/redis/go-redis/discussions/2744

<div type='discussions-op-text'>

<sup>Originally posted by **numberinho** October  6, 2023</sup>
I'm trying to HSet() structs with pointers.

Example:

```
cl := redis.NewClient(&redis.Options{
	Addr:     "localhost:6386",
	Password: "", // no password set
	DB:       0,  // use default DB
	PoolSize: 100,
})

type pointer struct {
	PtrInt *int    `redis:"ptrInt"`
	PtrStr *string `redis:"ptrStr"`
}

i := 1
s := "s"
p := pointer{&i, &s}

err := cl.HSet(context.Background(), "key", p).Err()
fmt.Println(err)

// redis: can't marshal *int (implement encoding.BinaryMarshaler)
```

How would you solve this? In my current application I have to store like 30 different structs, all having pointers to "simple data types" like *string and *int. The marshaling of them would be a super cool feature!

Thank you!</div>

**Comment by tzq0301** [comment]
I create PR #2753 to fix it.

**Comment by tzq0301** [comment]
@vmihailenco @ofekshenawa
