### ISSUE TITLE
behavior that does not meet expectations with SETNX

### ISSUE THREAD

**Issue by hongjijun233** [redis/go-redis#2751]
Issue tracker is used for reporting bugs and discussing new features. Please use
[stackoverflow](https://stackoverflow.com) for supporting issues.

## Expected Behavior

it should return `false` when i `setnx` a key that still has ttl in redis

## Current Behavior

when i call `setnx` concurrency, it will return true while the key still has ttl in redis

## Steps to Reproduce
here is the test code:
```
wg := sync.WaitGroup{}
for i := 0; i < 100; i++ {
wg.Add(1)
go func(num int) {
	t.Logf("current i: %d", num)
	ret, err := redisClient.SetNX(context.Background(), "goredis:test", "goredis:test", time.Second*100)
	assert.NoError(t, err)
	if ret {
		t.Logf("setnx success: %d", num)
	} else {
		t.Logf("setnx failed: %d", num)
	}
	wg.Done()
}(i)
}
wg.Wait()
```

1. we can check the ttl for the key `goredis:test`:
![image](https://github.com/redis/go-redis/assets/33631099/b33fb7ee-9839-4cba-ade7-04c48378b670)
2. then we execute the code, we can find it will return true in a goroutine:
![image](https://github.com/redis/go-redis/assets/33631099/f11a2007-b921-4826-adbb-d8d26a97a476)

**Comment by tzq0301** [comment]
In my test code, only one goroutine succeeded in setting the unique-key with an expiration of 100s and all the following goroutines got `false` while trying to setnx. It seems that there is no wrong behavior? Or I got misunderstood? 

Here is my test code:

```go
import (
	"context"
	"sync"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/redis/go-redis/v9"
	"github.com/stretchr/testify/assert"
	"go.uber.org/atomic"
)

func TestSetNX(t *testing.T) {
	redisClient := redis.NewClient(&redis.Options{
		Addr:     "localhost:6379",
		Password: "",
		DB:       0,
	})

	uid := uuid.New().String()

	var successCount atomic.Int32
	var failCount atomic.Int32

	var wg sync.WaitGroup
	for i := 0; i < 100; i++ {
		wg.Add(1)
		go func(num int) {
			defer wg.Done()

			ret, err := redisClient.SetNX(context.Background(), uid, uid, time.Second*100).Result()
			assert.NoError(t, err)

			if ret {
				successCount.Inc()
			} else {
				failCount.Inc()
			}
		}(i)
	}
	wg.Wait()

	assert.EqualValues(t, 1, successCount.Load())
	assert.EqualValues(t, 99, failCount.Load())
}
```

**Comment by hongjijun233** [comment]
> In my test code, only one goroutine succeeded in setting the unique-key with an expiration of 100s and all the following goroutines got `false` while trying to setnx. It seems that there is no wrong behavior? Or I got misunderstood?
> 
> Here is my test code:


> ```go
> import (
> 	"context"
> 	"sync"
> 	"testing"
> 	"time"
> 
> 	"github.com/google/uuid"
> 	"github.com/redis/go-redis/v9"
> 	"github.com/stretchr/testify/assert"
> 	"go.uber.org/atomic"
> )
> 
> func TestSetNX(t *testing.T) {
> 	redisClient := redis.NewClient(&redis.Options{
> 		Addr:     "localhost:6379",
> 		Password: "",
> 		DB:       0,
> 	})
> 
> 	uid := uuid.New().String()
> 
> 	var successCount atomic.Int32
> 	var failCount atomic.Int32
> 
> 	var wg sync.WaitGroup
> 	for i := 0; i < 100; i++ {
> 		wg.Add(1)
> 		go func(num int) {
> 			defer wg.Done()
> 
> 			ret, err := redisClient.SetNX(context.Background(), uid, uid, time.Second*100).Result()
> 			assert.NoError(t, err)
> 
> 			if ret {
> 				successCount.Inc()
> 			} else {
> 				failCount.Inc()
> 			}
> 		}(i)
> 	}
> 	wg.Wait()
> 
> 	assert.EqualValues(t, 1, successCount.Load())
> 	assert.EqualValues(t, 99, failCount.Load())
> }
> ```

oh, Thank you for your test and reply!!!

yes, we will get 1 success and 99 failed in above code.

But in my understanding, the first time we set a key with 'NX' we will get 1 success and 99 failed. However, I think we will get 100 failed in the second time while this key has not expired, because the key still in redis, so all the goroutine will failed, right?

So in your code, could you use a certain key rather than `uuid` and retry again?

Or is there anything I'm not getting right?

thanks!

**Comment by x1nchen** [comment]
I have understood what you mean. @hongjijun233 

I made some modifications to @tzq0301's test code.

Now assume that before the test code is executed, `test-key` does not exist in redis.

```golang
package main

import (
	"context"
	"sync"
	"testing"
	"time"

	"github.com/redis/go-redis/v9"
	"github.com/stretchr/testify/assert"
	"go.uber.org/atomic"
)

func TestSetNX(t *testing.T) {
	redisClient := redis.NewClient(
		&redis.Options{
			Addr:     "localhost:6379",
			Password: "",
			DB:       0,
		},
	)

	uid := "test-Key"

	var successCount atomic.Int32
	var failCount atomic.Int32

	var wg sync.WaitGroup
	for i := 0; i < 100; i++ {
		wg.Add(1)
		go func(num int) {
			defer wg.Done()

			ret, err := redisClient.SetNX(context.Background(), uid, uid, time.Second*100).Result()
			assert.NoError(t, err)

			if ret {
				successCount.Inc()
			} else {
				failCount.Inc()
			}
		}(i)
	}
	wg.Wait()

	assert.EqualValues(t, 1, successCount.Load())
	assert.EqualValues(t, 99, failCount.Load())

	// reset counter
	successCount.Store(0)
	failCount.Store(0)

	// run again
	for i := 0; i < 100; i++ {
		wg.Add(1)
		go func(num int) {
			defer wg.Done()

			ret, err := redisClient.SetNX(context.Background(), uid, uid, time.Second*100).Result()
			assert.NoError(t, err)

			if ret {
				successCount.Inc()
			} else {
				failCount.Inc()
			}
		}(i)
	}
	wg.Wait()
	assert.EqualValues(t, 0, successCount.Load())
	assert.EqualValues(t, 100, failCount.Load())
}
```

This test has passed for me. The behavior of setnx is not a problem.

Looking at your case again, could it be that the test code was executed only after the key `goredis:test` expired?

**Comment by hongjijun233** [comment]
@x1nchen yes, you are right. I found that this issue may caused by vscode...

I add `redisClient.TTL(ctx, key)` before execute `redisClient.SetNX(context.Background(), uid, uid, time.Second*100)`, the program will return error response when I simply **run** this test case(however, it will return correct response when I **debug** this test case)

I guess vscode will use **cached result** rather than reexecute again while it's test case has passed, so wired...

**Comment by hongjijun233** [comment]
I will close this issue, thanks @tzq0301 @x1nchen
