### ISSUE TITLE
9.5.0version  do panic

### ISSUE THREAD

**Issue by lala0257** [redis/go-redis#2918]
FAIL: TestRedis (0.32s)
panic: ERR Unknown subcommand or wrong number of arguments for 'setinfo'. Try CLIENT HELP [recovered]
	panic: ERR Unknown subcommand or wrong number of arguments for 'setinfo'. Try CLIENT HELP

**Comment by gongjiehong** [comment]
I also encountered a similar situation. 
It worked very well in version 9.4.0. 
After the upgrade, the commands used all reported errors: 
`ERR Syntax error, try CLIENT (LIST | KILL ip:port | GETNAME | SETNAME connection-name)`

**Comment by softwarespot** [comment]
Related https://github.com/redis/go-redis/issues/2911

**Comment by lala0257** [comment]
@softwarespot  thanks
