### ISSUE TITLE
Connection using unix-socket

### ISSUE THREAD

**Issue by gurre** [redis/go-redis#3]
Is it possible to connect using a unix-socket instead of TCP?

**Comment by SYNchroACK** [comment]
```
  r := redis.NewClient(&redis.Options{
    Network:  "unix",
    Addr:     "/var/run/redis/redis.sock",
    Password: "",
    DB:       "1",
  })
```

**Comment by totoyotonet** [comment]
r := redis.NewClient(&redis.Options{
    Network:  "unix",
    Addr:     "/var/run/redis/redis.sock",
    Password: "",
    DB:       "1",
  })
#
