### ISSUE TITLE
Extra related packages cannot obtain the latest version

### ISSUE THREAD

**Issue by shuqingzai** [redis/go-redis#3010]
Issue tracker is used for reporting bugs and discussing new features. Please use
[stackoverflow](https://stackoverflow.com) for supporting issues.

Using `go get -u xxx` to get the latest Extra pkg does not work

```bash
go get -u github.com/redis/go-redis/extra/redisotel/v9
```

The latest version should be [v9.5.2](https://github.com/redis/go-redis/releases/tag/v9.5.2)

What I see in [pkg.go.dev](https://pkg.go.dev/) is v9.0.5

- https://pkg.go.dev/github.com/redis/go-redis/extra/redisotel/v9#section-readme
- https://pkg.go.dev/github.com/redis/go-redis/extra/redisprometheus/v9#section-readme
- https://pkg.go.dev/github.com/redis/go-redis/extra/rediscensus/v9#section-readme
- https://pkg.go.dev/github.com/redis/go-redis/extra/rediscmd/v9#section-readme

<img width="430" alt="image" src="https://github.com/redis/go-redis/assets/44406033/03772ee3-5d46-4c6a-8800-7f7c5edf417f">

How can I get the latest version of the code?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by monkey92t** [comment]
@vmihailenco release new version?

**Comment by vmihailenco** [comment]
@monkey92t https://github.com/redis/go-redis/pull/3018
