### ISSUE TITLE
gitea redis cluster for non-HA case

### ISSUE THREAD

**Issue by Mohanraj4581** [redis/go-redis#3058]
Issue Description:
When attempting to use a Redis cluster with Gitea for a non-HA (1 node) scenario with a replica count of 1, the setup is not functioning correctly.

Steps to Reproduce:
Acquired the Gitea HA resources from the repository: [Gitea Helm Chart Repo](https://gitea.com/gitea/helm-chart/src/branch/gitea-ha)
Modified the replica count to 1 for all resources.
Applied the changes using kubectl apply.

Environment:
Kubernetes environment in bare metal

Detailed Description:
Upon applying the modified configuration, the Gitea pod and Redis cluster pod are stuck in a crash loop. The Gitea logs indicate a failure to connect to the Redis cluster. Although the Redis cluster logs do not show any error, the description reveals a readiness probe failure.

Request:
Please provide guidance on configuring the Redis cluster for a non-HA scenario with Gitea.

**Comment by monkey92t** [comment]
I see that you are using the https://charts.bitnami.com/bitnami redis helm in your Helm chart. Perhaps you should seek help there. go-redis only works as a client.

**Comment by Mohanraj4581** [comment]
ok 
thanks
