### ISSUE TITLE
can provide commands without context arg?

### ISSUE THREAD

**Issue by yoyoFighting123** [redis/go-redis#3072]
old code is based v3, not use context. But in V9, commands func has context arg, such as HGET  GET.
could use  context.Background()  like this to keep compatibility.

func (c cmdable) HSet(key string, values ...interface{}) *IntCmd {
	ctx := context.Background()
	args := make([]interface{}, 2, 2+len(values))
	args[0] = "hset"
	args[1] = key
	args = appendArgs(args, values)
	cmd := NewIntCmd(ctx, args...)
	_ = c(ctx, cmd)
	return cmd
}

**Comment by sgp** [comment]
Wouldn't this just make a mess of the interface? 

As the caller, you're free to supply `context.Background()` when you call any of these commands if you don't need context propagation.
