### ISSUE TITLE
Typo in FT.CREATE command (SEPARATOR vs SEPERATOR)

### ISSUE THREAD

**Issue by zhenghaoz** [redis/go-redis#3150]
The keyword for separator is `SEPARATOR` rather than `SEPERATOR`.

## Expected Behavior

https://redis.io/docs/latest/commands/ft.create/

> SEPARATOR {sep} for TAG attributes, indicates how the text contained in the attribute is to be split into individual tags. The default is ,. The value must be a single character.

## Current Behavior

https://github.com/redis/go-redis/blob/ad131f49b0210b3252648b880921b9f6d2fe452e/search_commands.go#L1006-L1008

## Possible Solution

Fix the typo from `SEPERATOR ` to `SEPERATOR`.

**Comment by vladvildanov** [comment]
This issue is fixed as a part of #3132
