### ISSUE TITLE
Many "you open connections too fast" errors

### ISSUE THREAD

**Issue by dim** [redis/go-redis#36]
We use the client in a high-frequency environment and the pools tend to grow quite quickly, especially on "boot". In these situation, we experience quite a few "you open connections too fast" errors, but I am not sure I understand the rationale behind the rate limiter. Could you please explain?

**Comment by lorieri** [comment]
Hi, I came to this issue with similar problem.
Just to help any other person that come here, the real problem was a connection failure and the subsequent requests happening too fast.

Check if you are still connect if you get this error.

cheers

**Comment by vmihailenco** [comment]
Thanks for the hint. I've sent https://github.com/go-redis/redis/pull/62 to help diagnose the cause.

**Comment by kokizzu** [comment]
@dim what did you do to solve this issue?

I have the same issue (randomly) when server restarts.
`Unknown Error: redis: you open connections too fast (last_error=\"dial tcp [::1]:6379: getsockopt: connection refused\"`

**Comment by kokizzu** [comment]
Ah, this is probably my fault *__*) when I use `localhost:6379` it shows those errors, when I use `127.0.0.1:6379` the library works fine..
