### ISSUE TITLE
Add support for ReJSON Module

### ISSUE THREAD

**Issue by NoSQLKnowHow** [redis/go-redis#597]
Is there any way for the future to add support for the ReJSON module http://rejson.io/ ?

**Comment by vmihailenco** [comment]
API is rather simple and small and I'd like to have it since go-redis does not provide any special support for storing structs in Redis. So rejson can be a nice addition. I am not sure when I will have time to do it so feel free to send PR :)

**Comment by KromDaniel** [comment]
https://github.com/KromDaniel/rejonson

I wrote a library that extends go-redis and also added at the https://oss.redislabs.com/rejson/#client-libraries docs

Enjoy
