### ISSUE TITLE
is there plan support tracing

### ISSUE THREAD

**Issue by FlamingTree** [redis/go-redis#616]
there is not method to pass tracing context to function, or is there other method

**Comment by vmihailenco** [comment]
There is `redis.WithContext()`, but it is just for passing context around. I don't plan to add tracing any time soon...

**Comment by vmihailenco** [comment]
FYI https://github.com/smacker/opentracing-go-redis looks reasonably good

**Comment by FlamingTree** [comment]
> FYI https://github.com/smacker/opentracing-go-redis looks reasonably good

but there is no way to trace pool related operation, such as time to get connection from pool, or time to  establish new connection

**Comment by aspacca** [comment]
@FlamingTree I'm working on this https://github.com/aspacca/apmgoredis
