### ISSUE TITLE
Add support for XInfo command

### ISSUE THREAD

**Issue by leenux** [redis/go-redis#914]
I can't find XINFO command

**Comment by luizvnasc** [comment]
Trying to use custom command to get the stream's info:

```
xInfo := func(stream string) *redis.StringCmd {
		cmd := redis.NewStringCmd("xinfo stream", stream)
		r.client.Process(cmd)
		return cmd
	}

```
I'm getting this error:

`ERR unknown command `xinfo stream`, with args beginning with: `TestStream``

**Comment by vmihailenco** [comment]
Try `redis.NewStringCmd("xinfo", "stream", stream)`

**Comment by luizvnasc** [comment]
> Try `redis.NewStringCmd("xinfo", "stream", stream)`

Worked like a charm. Thanks!

**Comment by Yagger** [comment]
@luizvnasc, when I use `xInfo` function in the following way:

```
v, err := xInfo("mystream").Result()
fmt.Println("Err: ", err)
fmt.Println("Value: ", v)
```

I get the following output:

```
Err:  redis: can't parse reply="*14" reading string
Value:
```

Since it worked for you, maybe you can point out if I am missing something. Thanks!
